<?php
/*
 * Created on 21-Jan-2006
 *
 * Display error message to user
 */
 include "main_include.phtml";
 
 
?>
<html>
<? print_top_frame($selfPath,  "./", false, false); ?>

<head>
<title><?= get_project_name($PHP_SELF);?> - Login</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body text="#000000" link="#0000FF" alink="#0000FF" vlink="#0000FF" bgcolor="#FFFFFF">
<center>
<table height="100%" width="100%">
	<tr>
		<td align="center" valign="center">
			<table cellspacing="0" cellpadding="0" border="0" width="700" height="10">
				<td align="left" valign="bottom"><img src="images/project-logo-small.jpg"></td>
				<td></td>
			</tr>
			<tr><td><br></td></tr>
			<tr><td>
				<BR><BR><BR><BR><BR><BR><BR><BR><BR>
				<? displayError(); ?>
				</font><br></td>
			</tr>
			<tr>
				<td>Click <a href=<?= ROOT_URL;?>>here</a> to login</td>
			</tr>
		</td>
	</tr>
</table>
</center>
</body>

</html>
