<?
// generate NSF cheque report

include "main_include.phtml";
// set the security level to be 3 for this page
check_auth(2);

$sql = "SELECT 	UserID,
				Company,
				LastName,
				FirstName,
				UnitNumber,
				Price, 
				ChequeNumber,
				ChequeAmount,
				ChequeDate
				FROM Cheque, User
				WHERE ChequeStatus = '" . CHEQUE_STATUS_NSF . "'
				AND DealStatus != 'Rescinded'
				AND (TransactionsRecordID = AgreementDepositTransactionsRecordID
				OR TransactionsRecordID = Day30DepositTransactionsRecordID
				OR TransactionsRecordID = Day90DepositTransactionsRecordID
				OR TransactionsRecordID = Day150DepositTransactionsRecordID
				OR TransactionsRecordID = Day210DepositTransactionsRecordID
				OR TransactionsRecordID = OccupancyDepositTransactionsRecordID)";

if (!isSet($listall)) // if not list all records, use the search criteria to do the search

{

	$values=$_GET;

	$search_criterion = "";

	$hasSearchValue = false;

	//loop that adds the field names and values

	foreach($values as $key=>$val)
	{
		$pos = strpos($key, "_");

		if ($pos > 0)
		{
			if ($val != "")
			{
				$hasSearchValue = true;
				$search_field = substr($key, $pos + 1);
				$sql_cond .= " AND (" . expandSearchCriteria(array("columnName"=>$search_field, "csvValue"=>$val)) . ") ";				
				$sql .= $sql_cond;				
				$search_criterion .= "&" . $key . "=" . $val;
			}
		}
	}
}

// list all
else
{
	$hasSearchValue = true;
	$search_criterion .= "&listall=1";
}

if ($orderby != "")
{
	$sql .= " ORDER BY $orderby," . getOrderClause(array("columnName"=>"User.UnitNumber", "sortMethod"=>DB_SORT_METHOD_VARCHAR_AS_NUMBER));
}
else
{
	$sql .= " ORDER BY " . getOrderClause(array("columnName"=>"User.UnitNumber", "sortMethod"=>DB_SORT_METHOD_VARCHAR_AS_NUMBER));
}
?>

<HTML>
<? print_top_frame($PHP_SELF, "./"); ?>
	<TITLE>NSF Cheque Report</TITLE>

		<DIV id="search" name="search">
<?
createCollapsibleDIVIcon("Search Criteria", "SearchCriteriaDIV");
createCollapsibleDIV("SearchCriteriaDIV"); 
?>
		<FORM NAME="form_search" METHOD="GET" ACTION="<?= $PHP_SELF; ?>">
			<TABLE>
			<INPUT TYPE="HIDDEN" NAME="orderby" VALUE="<?= $orderby;?>">
			<TR CLASS="blank">
				<TD>Suite Number: <BR>e.g. B1-%, B11-1~B2-3,B4-5,B6-1</TD>
				<TD><INPUT TYPE="TEXT" NAME="search_UnitNumber" VALUE="<?= $search_UnitNumber; ?>"></TD>
				<TD>First Name : </TD>
				<TD><INPUT TYPE="TEXT" NAME="search_FirstName" VALUE="<?= $search_FirstName; ?>"></TD>
				<TD>Last Name : </TD>
				<TD><INPUT TYPE="TEXT" NAME="search_LastName" VALUE="<?= $search_LastName; ?>"></TD>
			</TR>
			<TR CLASS="blank">
				<TD>Company: </TD>
				<TD><INPUT TYPE="TEXT" NAME="search_Company" VALUE="<?= $search_Company; ?>"></TD>
			</TR>
			<TR CLASS="blank">
				<TD COLSPAN=6 ALIGN="LEFT">Note : Use % as a wildcard character</TD>
			</TR>
			<TR>
				<TD COLSPAN="6" ALIGN="LEFT" CLASS="blank">
					<INPUT TYPE="SUBMIT" VALUE="Search">
					<INPUT TYPE="BUTTON" VALUE="List All" onClick="window.location='<?= $PHP_SELF; ?>?listall=1&orderby=<?= $orderby; ?>'">
					<INPUT TYPE="BUTTON" VALUE="Dump Data" onClick="window.location='dumpCSVnfsCheque.phtml'">
				</TD>
			</TR>
				
			</TABLE>
		</FORM>
	</DIV>
	</DIV>

<?
	// if no search criteria, don't do any search
	if ($hasSearchValue == false)

	{
		die("");
	}
?>	

	<H4>List NFS Cheques</H4>
	<TABLE>
<?
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);

	$totalChequeAmount = 0;
	$totalSalePrice = 0;
	
	$num_of_rows = 0;
	
	while ($row = mysql_fetch_array($result))
	{
		if ($num_of_rows++ % DEFAULT_NUM_OF_ROWS_TO_DISPLAY_HEADER == 0)
		{
?>
		<TR CLASS="head">
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=">Suite Number</A></TD>
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=Company">Company</TD>
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=FirstName, LastName"">Purchaser</TD>
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=Price">Sale Price</TD>
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=ChequeNumber">Cheque Number</TD>
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=ChequeAmount">Cheque Amount</TD>
			<TD><A HREF ="<?= $PHP_SELF . "?" .$search_criterion; ?>&orderby=ChequeDate">Received Date</TD>
		</TR>
<?
		}
		
		$totalChequeAmount += $row["ChequeAmount"];
		$totalSalePrice += $row["Price"];
		
		displayMouseOverTR("blank", "body");
?>

		<TD><?= $row["UnitNumber"]; ?></TD>
		<TD><?= $row["Company"]; ?></TD>
		<TD><A HREF="./userListing.phtml?action=display&mode=purchaser&UserID=<?= $row["UserID"] ?>"><?= $row["FirstName"] . " " . $row["LastName"] ?></A>
		<TD><? display_dollar_format($row["Price"]) ;?></TD>
		<TD><?= $row["ChequeNumber"]; ?></TD>
		<TD><? display_dollar_format($row["ChequeAmount"]); ?></TD>
		<TD><?= $row["ChequeDate"]; ?></TD>
	</TR>

<?
	}
?>
		
		<tr class=tail>
			<td align="right"><?= numberFormat(array("value"=>$num_of_rows)); ?></td>
			<td colspan="2" align="left">&nbsp;</td>
			<td align="right"><?= numberFormat(array("value"=>$totalSalePrice, "isDollarValue"=>TRUE)); ?></td>
			<td colspan="1">&nbsp;</td>
			<td align="right"><?= numberFormat(array("value"=>$totalChequeAmount, "isDollarValue"=>TRUE)); ?></td>
			<td colspan="1">&nbsp;</td>
		</tr>

	</TABLE>
</BODY>
</HTML>
