<?
include "main_include.phtml";
// set the security level to be 3 for this page
check_auth(ADMIN);

$currentDate = strtotime(date("Y-M-d"));

$search_date_from = $_GET["search_from"];
$search_date_to = $_GET["search_to"];

//SEARCH DATE FROM
if ($search_date_from == "") // if no date is assigned, set the date to "1980-01-01"
{	
	$search_date_from = "1980-01-01";
}	

//SEARCH DATE TO
if ($search_date_to == "") // if no date is assigned, set the date to be current date
{	
	$search_date_to = date("Y-m-d");		
}	
	$sql = "SELECT 	Unit.UnitNumber,
					Unit.Price As UnitPrice, 
					User.Price As UserPrice, 
					User.OfferPrice AS UserOfferPrice,		
					(User.Price / Unit.Area) AS AvgPricePerSqFeet,
					Unit.UnitType, 
					Unit.Model, 
					Unit.UnitTypeDescription,
					Unit.Area, 
					Unit.Status,
					User.LastName,
					User.FirstName,
					User.AgreementDepositDate,
					User.RescissionDate,
					User.DealStatus,
					User.UserID,
					User.UnitAllowance,
					User.ParkingSpaceCharge,
					User.LockerCharge,
					User.AdditionalCost
					FROM Unit LEFT JOIN User 
					ON Unit.UserID = User.UserID
					AND User.AgreementDepositDate <= \"$search_date_to\" 
					AND User.AgreementDepositDate >= \"$search_date_from\" ";

if ($orderby != "")
{
	$sql .= " ORDER BY $orderby";
}
else
{
	$sql .= " ORDER BY Unit.UnitNumber, LastName, FirstName";
}
	$result = executeSql($sql);
	
?>
<HTML>
<? print_top_frame($PHP_SELF, "./"); ?>



<DIV id="search" name="search">
<?
createCollapsibleDIVIcon("Search Criteria", "SearchCriteriaDIV");
createCollapsibleDIV("SearchCriteriaDIV"); 
?>
	<TITLE>Sales Status</TITLE>	
	
	<? if ($search_date_from == "1980-01-01") //Do not display default value for $search_date_from
	{
		?> <H3><?= get_project_name($PHP_SELF); ?> -- Sales Status as at <?= convert_date($search_date_to, "english") ?> </H3> 
			<TABLE>
				<TR><TD></TD></TR>
				<FORM NAME="form_search_by_date" METHOD="GET" ACTION="<?= $PHP_SELF; ?>">
				<TR CLASS="blank">
				<TD>Search From :<BR>(YYYY-MM-DD) </TD>
				<TD><INPUT TYPE=TEXT NAME="search_from"></TD>
				<TD align=right>To :<BR>(YYYY-MM-DD) </TD>
				<TD><INPUT TYPE=TEXT NAME="search_to" VALUE=<?= $search_date_to ?>></TD>
	        		</TR>
	        		<TR>
				<TD><INPUT TYPE="SUBMIT" VALUE="Search"></TD>	
				<? $date_to_search = $search_date_to; ?>
			        <TD colspan="3"><INPUT TYPE="BUTTON" VALUE="Dump Data" onClick="window.location='./dumpCSVSaleStatus.phtml?date_to_search=<?= $date_to_search; ?>'"></TD>	
				</TR>
				</FORM>
			</TABLE> <?
	}
	else
	{
	 	?> <H3><?= get_project_name($PHP_SELF); ?> -- Sales Status from <?= convert_date($search_date_from, "english") ?> 
	                                                        to <?= convert_date($search_date_to, "english") ?> </H3> 
	                <TABLE>
				<TR><TD></TD></TR>
				<FORM NAME="form_search_by_date" METHOD="GET" ACTION="<?= $PHP_SELF; ?>">
				<TR CLASS="blank">
				<TD>Search From :<BR>(YYYY-MM-DD) </TD>
				<TD><INPUT TYPE=TEXT NAME="search_from" VALUE=<?= $search_date_from?>></TD>
				<TD align=right>To :<BR>(YYYY-MM-DD) </TD>
				<TD><INPUT TYPE=TEXT NAME="search_to" VALUE=<?= $search_date_to ?>></TD>
	        		</TR>
	        		<TR>
				<TD><INPUT TYPE="SUBMIT" VALUE="Search"></TD>		
				<? $date_to_search = $search_date_to; ?>
			        <TD colspan="3"><INPUT TYPE="BUTTON" VALUE="Dump Data" onClick="window.location='./dumpCSVSaleStatus.phtml?date_to_search=<?= $date_to_search; ?>'"></TD>
				</TR>
				</FORM>
			</TABLE> <?
	} ?>
	</DIV>
</DIV>
	
	<TABLE>		
<?

	$totalUnitPrice = 0;
	$totalSalesPrice = 0;
	$totalUnitAllowance = 0;
	$totalParkingSpaceCharge = 0;
	$totalLockerCharge = 0;
	$totalAdditionalCost = 0;
	$totalNetPrice = 0;
	$netPrice = 0;
	$totalOfferPrice = 0;
	$totalArea = 0;
	$totalAvgPricePerSqFeet = 0;
	$num_of_rows = 0;
	
	while ($row = mysql_fetch_array($result))
	{
		if ($num_of_rows++ % DEFAULT_NUM_OF_ROWS_TO_DISPLAY_HEADER == 0)
		{
?>
		<TR CLASS="head">
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=UnitNumber, FirstName,LastName">Unit</A></TD>
			<TD>Latest Price</TD>
			<TD>Latest Price/Sold Price</TD>
			<TD>Offer Price</TD>
			<TD>Unit Allowance</TD>
			<TD>Parking Charge</TD>
			<TD>Locker Charge</TD>
			<TD>Additional Cost</TD>
			<TD>Total Unit Sales</TD>
			<TD>Avg. Price Per Sq Feet</TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=UnitType, UnitNumber, FirstName,LastName">Type</A></TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=Area, UnitNumber, FirstName,LastName">Size</A></TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=FirstName,LastName, UnitNumber">Purchaser</A></TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=AgreementDepositDate, UnitNumber, FirstName,LastName">Offer Date</A></TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=RescissionDate, UnitNumber, FirstName,LastName">Rescission Date</A></TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=DealStatus, UnitNumber, FirstName,LastName">Deal Status</A></TD>
			<TD><A HREF ="<?= $PHP_SELF;?>?orderby=Status, UnitNumber, FirstName,LastName">Reserve Status</a></TD>
		</TR>
<?
		}
		$netPrice = 0;	
		displayMouseOverTR("blank", "body");		
?>
			<TD><?= $row['UnitNumber']; ?></TD>
			<TD><?
				if ($row['UnitPrice'] != "")
				{
					echo display_dollar_format($row['UnitPrice']) ;
					$totalUnitPrice += $row['UnitPrice'];
				}
				else
				{
					echo "";
				}
			?></TD>
			<TD><? 
				if ($row['UserPrice'] != "")
				{
					echo display_dollar_format($row['UserPrice']);
					$netPrice += $row['UserPrice'];
					$totalSalesPrice += $row['UserPrice'];
				}
				else
				{
					echo display_dollar_format($row['UnitPrice']); 
					$totalSalesPrice += $row['UnitPrice'];					
				}
			?></TD>
			<TD><? if ($row['UserOfferPrice'] != "") {
					echo display_dollar_format($row['UserOfferPrice']);
				} 
				$totalOfferPrice += $row['UserOfferPrice'];
			?></TD>
			<TD><? 
				if ($row['UnitAllowance'] != "")
				{
					echo display_dollar_format($row['UnitAllowance']) ;
					$netPrice -= $row['UnitAllowance'];
					$totalUnitAllowance += $row['UnitAllowance'];
				}
				else
				{
					echo "";
				}
			?></TD>
			<TD><? 
				if ($row['ParkingSpaceCharge'] != "")
				{
					echo display_dollar_format($row['ParkingSpaceCharge']);
					$netPrice += $row['ParkingSpaceCharge'];
					$totalParkingSpaceCharge += $row['ParkingSpaceCharge'];
				}
				else
				{
					echo "";
				}
			?></TD>
			<TD><? 
				if ($row['LockerCharge'] != "")
				{
					echo display_dollar_format($row['LockerCharge']);
					$netPrice += $row['LockerCharge'];
					$totalLockerCharge += $row['LockerCharge'];
				}
				else
				{
					echo "";
				}
			?></TD>
			<TD><? 
				if ($row['AdditionalCost'] != "")
				{
					echo display_dollar_format($row['AdditionalCost']);
					$netPrice += $row['AdditionalCost'];
					$totalAdditionalCost += $row['AdditionalCost'];
				}
				else
				{
					echo "";
				}
			?></TD>			
			<TD><?
				if ($row['UserPrice'] != "")
				{
					echo display_dollar_format($netPrice);
					$totalNetPrice += $netPrice;
				}
			?></TD>
			<TD><?
				if ($row['AvgPricePerSqFeet'] != "")
				{
					echo display_dollar_format($row['AvgPricePerSqFeet']);
					$totalAvgPricePerSqFeet += $row['AvgPricePerSqFeet'];
				}
			?></TD>			
			<TD><?= $row['UnitType']; ?></TD>
			<TD><?= $row['Area']; $totalArea += $row['Area']; ?></TD>
			<TD><?
			if ($row['FirstName'] != "")
			{
				$url = "./userListing.phtml?action=display&mode=purchaser&UserID=" . $row['UserID'];			
				echo "<A HREF=\"" . $url . "\">" . $row['LastName'] . ", " . $row['FirstName'] . "</A>";
			}
			?></TD>
			<TD nowrap><?= convert_date($row['AgreementDepositDate']); ?></TD>
			<TD nowrap><?= convert_date($row['RescissionDate']); ?></TD>
			<TD><?
				echo $row['DealStatus'];
				if ($row['DealStatus'] == "Pending" && $currentDate > strtotime ($row['RescissionDate']) )
				{
					echo " <font color=red>Overdue</font>";
				}
			?></TD>	
			<TD><?
				if ($row["Status"] == "Reserved") echo "<font color=red>Reserved</font>";
				else if ($row["Status"] == "On Hold Available" )	echo "<font color=red>Held</font>";
			?></TD>
		</TR>
<?
	}
?>

	<TR CLASS="tail">
		<TD><?= $num_of_rows ?></TD>
		<TD><?= display_dollar_format($totalUnitPrice); ?></TD>
		<TD><?= display_dollar_format($totalSalesPrice); ?></TD>
		<TD><?= display_dollar_format($totalOfferPrice); ?></TD>
		<TD><?= display_dollar_format($totalUnitAllowance); ?></TD>
		<TD><?= display_dollar_format($totalParkingSpaceCharge); ?></TD>
		<TD><?= display_dollar_format($totalLockerCharge); ?></TD>
		<TD><?= display_dollar_format($totalAdditionalCost); ?></TD>
		<TD><?= display_dollar_format($totalNetPrice); ?></TD>
		<TD><?= display_dollar_format($totalAvgPricePerSqFeet); ?></TD>
		<TD>&nbsp;</TD>		
		<TD><?= $totalArea; ?></TD>
		<TD COLSPAN=7>&nbsp;</TD>		
	</TR>
	</TABLE>

<?
if (MODEL_SALES_STATUS_ENABLED)
{
?>
	<H4>Summary by Model</H4>
	<TABLE>
		<TR CLASS="head">
			<TD>Model</TD>
			<TD>Type</TD>
			<TD>Type Desc.</TD>
			<TD>Firm</TD>
			<TD>Pending</TD>
			<TD>Corporate</TD>
			<TD>Overdue</TD>
			<TD>NotReportToHeadOffice</TD>
			<TD>Available</TD>
			<TD>Total</TD>
			<TD>% Firm Sales by # of units</TD>
		</TR>
<?
	$sql = "SELECT *
			FROM Unit LEFT JOIN User 
			ON Unit.UserID = User.UserID 
			AND User.AgreementDepositDate <= \"$date\" 
			ORDER BY Model";
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);

	$ModelTotal 		= 0;
	$ModelAvailable 	= 0;
	$ModelPending 	= 0;
	$ModelOverdue 	= 0;
	$ModelCorporate 	= 0;
	$ModelFirm 		= 0;
	$ModelNotReportToHeadOffice = 0;
	
	$TotalModelTotal 	= 0;
	$TotalUnitTypeAvailable = 0;
	$TotalUnitTypePending = 0;
	$TotalUnitTypeOverdue 	= 0;
	$TotalUnitTypeCorporate 	= 0;
	$TotalUnitTypeFirm 		= 0;
	$TotalUnitTypeNotReportToHeadOffice = 0;

	while ($row = mysql_fetch_array($result))
	{
		if ($Model != $row['Model'] && isSet($Model) && ltrim(rtrim($Model)) != "")
		{
		displayMouseOverTR("blank", "body");		
?>
				<TD><?= $Model; ?></TD>
				<TD><?= $UnitType; ?></TD>
				<TD><?= $UnitTypeDescription; ?></TD>
				<TD><?= $ModelFirm; ?></TD>
				<TD><?= $ModelPending; ?></TD>
				<TD><?= $ModelCorporate; ?></TD>
				<TD><?= $ModelOverdue; ?></TD>
				<TD><?= $ModelNotReportToHeadOffice; ?></TD>
				<TD><?= $ModelAvailable; ?></TD>
				<TD><?= $ModelTotal; ?></TD>
				<TD><?
				if ($ModelTotal == 0)
				{
					echo "0";
				}
				else
				{
					echo number_format(($ModelFirm / $ModelTotal) * 100, 2); 
				}
				?></TD>

			</TR>
<?
			$TotalModelTotal 	+= $ModelTotal;
			$TotalModelAvailable += $ModelAvailable;
			$TotalModelPending += $ModelPending;
			$TotalModelCorporate += $ModelCorporate;
			$TotalModelOverdue 	+= $ModelOverdue;
			$TotalModelFirm 		+= $ModelFirm;
			$TotalModelNotReportToHeadOffice 		+= $ModelNotReportToHeadOffice;

			$Model = $row['Model'];
			$ModelTotal	= 0;
			$ModelAvailable 	= 0;
			$ModelPending 	= 0;
			$ModelOverdue 	= 0;
			$ModelFirm 		= 0;
			$ModelCorporate = 0;
			$ModelNotReportToHeadOffice = 0;
		}

			$Model = $row['Model'];
			$UnitType = $row['UnitType'];
			$UnitTypeDescription = $row['UnitTypeDescription'];
			$ModelTotal++;
			if ($row['FirstName'] == "")
			{
				$ModelAvailable++;
			}
			else if ($row['DealStatus'] == "Firm")
			{ // Firm
				$ModelFirm++;
			}
			else if ($row['DealStatus'] == "NotReportToHeadOffice")
			{ // NotReportToHeadOffice
				$ModelNotReportToHeadOffice++;
			}
			else if ($row['DealStatus'] == "Corporate")
			{ // Corporate Deal
				$ModelCorporate++;
			}			
			else if ($currentDate <= strtotime ($row['RescissionDate']) && $row['DealStatus'] == "Pending")			
			{ // pending // no more check  $row['RescissionFlag'] == 1
				$ModelPending++;
			}
			// before was DealStatus != Firm, or == panding but todays date is past the rescission date
			else 
			{ // overdue
				$ModelOverdue++;
			}
	}
	
	// print out the last unit type information after the loop ends
	if (isSet($Model) && ltrim(rtrim($Model)) != "")
	{
		displayMouseOverTR("blank", "body");		
?>
				<TD><?= $Model; ?></TD>
				<TD><?= $UnitType; ?></TD>
				<TD><?= $UnitTypeDescription; ?></TD>
				<TD><?= $ModelFirm; ?></TD>
				<TD><?= $ModelPending; ?></TD>
				<TD><?= $ModelCorporate; ?></TD>
				<TD><?= $ModelOverdue; ?></TD>
				<TD><?= $ModelNotReportToHeadOffice; ?></TD>
				<TD><?= $ModelAvailable; ?></TD>
				<TD><?= $ModelTotal; ?></TD>
				<TD><?
				if ($ModelTotal == 0)
				{
					echo "0";
				}
				else
				{
					echo number_format(($ModelFirm / $ModelTotal) * 100, 2); 
				}
				?></TD>

			</TR>	
<?
			$TotalModelTotal 	+= $ModelTotal;
			$TotalModelAvailable += $ModelAvailable;
			$TotalModelPending += $ModelPending;
			$TotalModelCorporate += $ModelCorporate;
			$TotalModelOverdue 	+= $ModelOverdue;
			$TotalModelFirm 		+= $ModelFirm;
			$TotalModelNotReportToHeadOffice += $ModelNotReportToHeadOffice;
			
	}
			// total sales price
			$TotalModel	= $TotalModelFirm + $TotalModelPending + $TotalModelOverdue + $TotalCorporate + $TotalModelAvailable + $TotalModelNotReportToHeadOffice;

?>
			<TR CLASS=tail>
				<TD>Total</TD>
				<TD></TD>
				<TD></TD>
				<TD><?= $TotalModelFirm; ?></TD>
				<TD><?= $TotalModelPending; ?></TD>
				<TD><?= $TotalModelCorporate; ?></TD>
				<TD><?= $TotalModelOverdue; ?></TD>
				<TD><?= $TotalModelNotReportToHeadOffice; ?></TD>
				<TD><?= $TotalModelAvailable; ?></TD>
				<TD><?= $TotalModelTotal; ?></TD>
				<TD><?
				if ($TotalModelTotal == 0)
				{
					echo "0";
				}
				else
				{
					echo number_format((($TotalModelFirm+$TotalModelCorporate) / $TotalModelTotal) * 100, 2); 
				}
				?></TD>

			</TR>	
	</TABLE>
<?
}
?>
	<H4>Summary by Unit Type</H4>
	<TABLE>
		<TR CLASS="head">
			<TD>Unit Type</TD>
			<TD>Firm</TD>
			<TD>Pending</TD>
			<TD>Corporate</TD>
			<TD>Overdue</TD>
			<TD>NotReportToHeadOffice</TD>
			<TD>Available</TD>
			<TD>Total</TD>
			<TD>% Firm Sales by # of units</TD>
		</TR>
<?
	$sql = "SELECT *, User.Price As PurchaserPrice, Unit.Price As UnitPrice 
			FROM Unit LEFT JOIN User 
			ON Unit.UserID = User.UserID 			
			AND User.AgreementDepositDate >= \"$search_date_from\" 
			AND User.AgreementDepositDate <= \"$search_date_to\" 
			ORDER BY Unit.UnitType";
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);

	$UnitTypeTotal 		= 0;
	$UnitTypeAvailable 	= 0;
	$UnitTypePending 	= 0;
	$UnitTypeCorporate 	= 0;
	$UnitTypeOverdue 	= 0;
	$UnitTypeFirm 		= 0;
	$UnitTypeNotReportToHeadOffice = 0;
	
	$TotalUnitTypeTotal 	= 0;
	$TotalUnitTypeAvailable = 0;
	$TotalUnitTypeCorporate = 0;
	$TotalUnitTypePending = 0;
	$TotalUnitTypeOverdue 	= 0;
	$TotalUnitTypeFirm 		= 0;
	$TotalUnitTypeNotReportToHeadOffice = 0;

	$TotalFirmSize		= 0;
	$TotalAvailableSize = 0;
	$TotalPendingSize	= 0;
	$TotalCorporateSize	= 0;
	$TotalOverdueSize	= 0;
	$TotalNotReportToHeadOfficeSize	= 0;

	$TotalFirmSalesPrice		= 0;
	$TotalAvailableSalesPrice	= 0;
	$TotalPendingSalesPrice	= 0;
	$TotalCorporateSalesPrice	= 0;
	$TotalOverdueSalesPrice		= 0;
	$TotalNotReportToHeadOfficeSalesPrice = 0;

	while ($row = mysql_fetch_array($result))
	{
		if ($UnitType != $row['UnitType'] && isSet($UnitType))
		{
		displayMouseOverTR("blank", "body");		
?>
				<TD><?= $UnitType; ?></TD>
				<TD><?= $UnitTypeFirm; ?></TD>
				<TD><?= $UnitTypePending; ?></TD>
				<TD><?= $UnitTypeCorporate; ?></TD>
				<TD><?= $UnitTypeOverdue; ?></TD>
				<TD><?= $UnitTypeNotReportToHeadOffice; ?></TD>
				<TD><?= $UnitTypeAvailable; ?></TD>
				<TD><?= $UnitTypeTotal; ?></TD>
				<TD><?
				if ($UnitTypeTotal == 0)
				{
					echo "0";
				}
				else
				{
					echo number_format(($UnitTypeFirm / $UnitTypeTotal) * 100, 2); 
				}
				?></TD>

			</TR>
<?
			$TotalUnitTypeTotal 	+= $UnitTypeTotal;
			$TotalUnitTypeAvailable += $UnitTypeAvailable;
			$TotalUnitTypePending += $UnitTypePending;
			$TotalUnitTypeCorporate += $UnitTypeCorporate;
			$TotalUnitTypeOverdue 	+= $UnitTypeOverdue;
			$TotalUnitTypeFirm 		+= $UnitTypeFirm;
			$TotalUnitTypeNotReportToHeadOffice 		+= $UnitTypeNotReportToHeadOffice;

			$UnitType = $row['UnitType'];
			$UnitTypeTotal 		= 0;
			$UnitTypeAvailable 	= 0;
			$UnitTypePending 	= 0;
			$UnitTypeCorporate 	= 0;
			$UnitTypeOverdue 	= 0;
			$UnitTypeFirm 		= 0;
			$UnitTypeNotReportToHeadOffice = 0;
		}

			$UnitType = $row['UnitType'];
			$UnitTypeTotal++;
			if ($row['FirstName'] == "")
			{
				$UnitTypeAvailable++;
				$TotalAvailableSize 		+= $row['Area'];
				$TotalAvailableSalesPrice	+= $row['UnitPrice'];
			}
			else if ($row['DealStatus'] == "Firm")
			{ // Firm
				$UnitTypeFirm++;
				$TotalFirmSize			+= $row['Area'];
				$TotalFirmSalesPrice 	+= $row['PurchaserPrice'];
			}
			else if ($row['DealStatus'] == "NotReportToHeadOffice")
			{ // NotReportToHeadOffice
				$UnitTypeNotReportToHeadOffice++;
				$TotalNotReportToHeadOfficeSize			+= $row['Area'];
				$TotalNotReportToHeadOfficeSalesPrice 	+= $row['PurchaserPrice'];
			}
			else if ($row['DealStatus'] == "Corporate"){
				$UnitTypeCorporate++;
				$TotalCorporateSize			+= $row['Area'];
				$TotalCorporateSalesPrice 	+= $row['PurchaserPrice'];
				
			}
			else if ($currentDate <= strtotime ($row['RescissionDate']) && $row['DealStatus'] == "Pending")			
			{ // pending // no more check  $row['RescissionFlag'] == 1
				$UnitTypePending++;
				$TotalPendingSize			+= $row['Area'];
				$TotalPendingSalesPrice	+= $row['PurchaserPrice'];			
			}
			// before was DealStatus != Firm, or == panding but todays date is past the rescission date
			else 
			{ // overdue

				$UnitTypeOverdue++;
				$TotalOverdueSize	+= $row['Area'];
				$TotalOverdueSalesPrice		+= $row['PurchaserPrice'];
			}
	}
	
	// print out the last unit type information after the loop ends
	if (isSet($UnitType))
	{
		displayMouseOverTR("blank", "body");		
?>
				<TD><?= $UnitType; ?></TD>
				<TD><?= $UnitTypeFirm; ?></TD>
				<TD><?= $UnitTypePending; ?></TD>
				<TD><?= $UnitTypeCorporate; ?></TD>
				<TD><?= $UnitTypeOverdue; ?></TD>
				<TD><?= $UnitTypeNotReportToHeadOffice; ?></TD>
				<TD><?= $UnitTypeAvailable; ?></TD>
				<TD><?= $UnitTypeTotal; ?></TD>
				<TD><?
				if ($UnitTypeTotal == 0)
				{
					echo "0";
				}
				else
				{
					echo number_format(($UnitTypeFirm / $UnitTypeTotal) * 100, 2); 
				}
				?></TD>

			</TR>	
<?
			$TotalUnitTypeTotal 	+= $UnitTypeTotal;
			$TotalUnitTypeAvailable += $UnitTypeAvailable;
			$TotalUnitTypePending += $UnitTypePending;
			$TotalUnitTypeCorporate += $UnitTypeCorporate;
			$TotalUnitTypeOverdue 	+= $UnitTypeOverdue;
			$TotalUnitTypeFirm 		+= $UnitTypeFirm;
			$TotalUnitTypeNotReportToHeadOffice += $UnitTypeNotReportToHeadOffice;
			
	}
			// total sales price
			$TotalUnit				= 	$TotalUnitTypeFirm + $TotalUnitTypePending + $TotalUnitTypeCorporate + $TotalUnitTypeOverdue + $TotalUnitTypeAvailable + $TotalUnitTypeNotReportToHeadOffice;
			$TotalSalesPrice		= 	$TotalFirmSalesPrice + $TotalAvailableSalesPrice + $TotalPendingSalesPrice + $TotalCorporateSalesPrice + $TotalOverdueSalesPrice + $TotalNotReportToHeadOfficeSalesPrice;
			$TotalSize				= 	$TotalFirmSize + $TotalPendingSize + $TotalCorporateSize + $TotalOverdueSize + $TotalAvailableSize + $TotalNotReportToHeadOfficeSize;

?>
			<TR CLASS=tail>
				<TD>Total</TD>
				<TD><?= $TotalUnitTypeFirm; ?></TD>
				<TD><?= $TotalUnitTypePending; ?></TD>
				<TD><?= $TotalUnitTypeCorporate; ?></TD>
				<TD><?= $TotalUnitTypeOverdue; ?></TD>
				<TD><?= $TotalUnitTypeNotReportToHeadOffice; ?></TD>
				<TD><?= $TotalUnitTypeAvailable; ?></TD>
				<TD><?= $TotalUnitTypeTotal; ?></TD>
				<TD><?
				if ($TotalUnitTypeTotal == 0)
				{
					echo "0";
				}
				else
				{
					echo number_format(($TotalUnitTypeFirm / $TotalUnitTypeTotal) * 100, 2); 
				}
				?></TD>

			</TR>	
	</TABLE>

<BR><BR>
<?
createCollapsibleDIVIcon('Summary by Deal Status','ReportTable'  . $reportTableIndex);
createCollapsibleDIV('ReportTable'  . $reportTableIndex++);
	include_once "Report/Model/RptDealStatusModel.phtml";
	include_once "Report/Controller/RptDealStatusController.phtml";
	include_once "Report/View/RptDealStatusView.phtml";

	$view = new RptDealStatusView();
	print $view->getRptHTML();
	print $view->getRptJS();
?>
</DIV>
	<BR><BR>
	<H4>Summary by Deal Status</H4>	
	<TABLE>
		<TR CLASS=head>
			<TD>Type</TD>
			<TD>#</TD>
			<TD>Size(sq.ft.)</TD>
			<TD>Sales Price</TD>
			<TD>Avg. Price/sq. ft.</TD>
			<TD>% by Value</TD>
		</TR>
<?				displayMouseOverTR("blank", "body");	 ?>
			<TD>Firm</TD>
			<TD><?= $TotalUnitTypeFirm; ?></TD>
			<TD><?= $TotalFirmSize; ?></TD>
			<TD><? display_dollar_format($TotalFirmSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalFirmSalesPrice, $TotalFirmSize));  ?></TD>
			<TD><?= calculate_percentage($TotalFirmSalesPrice, $TotalSalesPrice); ?></TD>
		</TR>
<?				displayMouseOverTR("blank", "body");	 ?>
			<TD>Pending</TD>
			<TD><?= $TotalUnitTypePending; ?></TD>
			<TD><?= $TotalPendingSize; ?></TD>
			<TD><? display_dollar_format($TotalPendingSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalPendingSalesPrice, $TotalPendingSize)); ?></TD>
			<TD><?= calculate_percentage($TotalPendingSalesPrice, $TotalSalesPrice) ; ?></TD>
		</TR>
<?				displayMouseOverTR("blank", "body");	 ?>
			<TD>Corporate</TD>
			<TD><?= $TotalUnitTypeCorporate; ?></TD>
			<TD><?= $TotalCorporateSize; ?></TD>
			<TD><? display_dollar_format($TotalCorporateSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalCorporateSalesPrice, $TotalCorporateSize)); ?></TD>
			<TD><?= calculate_percentage($TotalCorporateSalesPrice, $TotalSalesPrice) ; ?></TD>
		</TR>		
<?				displayMouseOverTR("blank", "body");	 ?>
			<TD>Overdue</TD>
			<TD><?= $TotalUnitTypeOverdue; ?></TD>
			<TD><?= $TotalOverdueSize; ?></TD>
			<TD><? display_dollar_format($TotalOverdueSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalOverdueSalesPrice, $TotalOverdueSize)); ?></TD>
			<TD><?= calculate_percentage($TotalOverdueSalesPrice, $TotalSalesPrice) ; ?></TD>
		</TR>
<?				displayMouseOverTR("blank", "body");	 ?>
			<TD>NotReportToHeadOffice</TD>
			<TD><?= $TotalUnitTypeNotReportToHeadOffice; ?></TD>
			<TD><?= $TotalNotReportToHeadOfficeSize; ?></TD>
			<TD><? display_dollar_format($TotalNotReportToHeadOfficeSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalNotReportToHeadOfficeSalesPrice, $TotalNotReportToHeadOfficeSize)); ?></TD>
			<TD><?= calculate_percentage($TotalNotReportToHeadOfficeSalesPrice, $TotalSalesPrice) ; ?></TD>
		</TR>
<?				displayMouseOverTR("blank", "body");	 ?>
			<TD>Available</TD>
			<TD><?= $TotalUnitTypeAvailable; ?></TD>
			<TD><?= $TotalAvailableSize; ?></TD>
			<TD><? display_dollar_format($TotalAvailableSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalAvailableSalesPrice, $TotalAvailableSize)); ?></TD>
			<TD><?= calculate_percentage($TotalAvailableSalesPrice, $TotalSalesPrice); ?></TD>
		</TR>
		<TR CLASS=tail>
			<TD>Total</TD>
			<TD><?= $TotalUnit; ?></TD>
			<TD><?= $TotalSize; ?></TD>
			<TD><? display_dollar_format($TotalSalesPrice); ?></TD>
			<TD><? display_dollar_format(calculate_division($TotalSalesPrice, $TotalSize)); ?></TD>
			<TD>100</TD>
		</TR>
	</TABLE>
	<BR><BR>
	
	<? 
	
	if (get_access_security_level() >= MANAGEMENT) {
	//if (True) {
		//echo (get_access_security_level());
	?>
	<DIV id="forecast" name="forecast">
	<?
	createCollapsibleDIVIcon("Sales Forcast Schedule", "SalesForcastScheduleDIV");
	createCollapsibleDIV("SalesForcastScheduleDIV"); 
	include ("./SalesSchedule/salesForecastSchedule.phtml");
	?>
		</DIV>
	</DIV>	
	
	<? 
	} 
	?>
	
	<H4>Sales Incentive</H4>	
	<TABLE>
		<TR CLASS=head>
			<TD COLSPAN="3">Unit Extras</TD>
		</TR>
		<TR CLASS=head>
			<TD>Parking Summary</TD>
			<TD>#</TD>
			<TD>Total</TD>
		</TR>
<?
	// var to store total value
	$totalNumber = 0;
	$totalValue = 0;

	$sql = "SELECT COUNT(UserID) As TotalNumber
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND ParkingIncludedInPrice = 1";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	$totalNumber += $row['TotalNumber'];
	displayMouseOverTR("blank", "body");	 
?>
			<TD><a href="optionSummary.phtml?Option=ParkingIncludedInPrice">Regular Parking Unit Included in Price</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD></TD>
		</TR>
<?
	$sql = "SELECT COUNT(UserID) As TotalNumber
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND ParkingSpace=1";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	$totalNumber += $row['TotalNumber'];
	displayMouseOverTR("blank", "body");	 
?>
			<TD><a href="optionSummary.phtml?Option=ParkingSpace">Extra Regular Parking Unit</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD></TD>
		</TR>
<?
	$sql = "SELECT COUNT(UserID) As TotalNumber
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND ParkingExtended=1";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	$totalNumber += $row['TotalNumber'];
	displayMouseOverTR("blank", "body");	 
?>
			<TD><a href="optionSummary.phtml?Option=ParkingExtended">Extended Parking Unit</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD></TD>
		</TR>
<?
	if (is_citygate_2($PHP_SELF))
	{
		$sql = "SELECT COUNT(UserID) As TotalNumber
			FROM User 
			WHERE (User.DealStatus=\"FIRM\"
				OR User.DealStatus=\"PENDING\"
				OR User.DealStatus=\"CORPORATE\")
				AND ParkingTandemUnit=1";
		
		$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
		$row = mysql_fetch_array($result);
		$totalNumber += $row['TotalNumber'];
	displayMouseOverTR("blank", "body");	 
?>
			<TD><a href="optionSummary.phtml?Option=ParkingTandemUnit">Tandem Parking Unit</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD></TD>
		</TR>
<?
	}
	
	$sql = "SELECT COUNT(UserID) As TotalNumber, 
			SUM(ParkingSpaceCharge) As TotalValue
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND ParkingSpaceCharge > 0";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	$totalNumber += $row['TotalNumber'];
	$totalValue += $row['TotalValue'] > 0 ? $row['TotalValue'] : 0;
	displayMouseOverTR("blank", "body");	 
	
?>
			<TD><a href="optionSummary.phtml?Option=ParkingSpaceCharge">Total Parking Units Sold</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD><?= display_dollar_format($row['TotalValue'] > 0 ? $row['TotalValue'] : 0); ?></TD>
		</TR>
<?
	$sql = "SELECT SUM(Locker) As TotalNumber, 
			SUM(LockerCharge) As TotalValue
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND Locker>0";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	
	$row['TotalNumber'] = is_null($row['TotalNumber']) ? 0 : $row['TotalNumber'];
	
	$totalNumber += $row['TotalNumber'];
	$totalValue += $row['TotalValue'] > 0 ? $row['TotalValue'] : 0;
	displayMouseOverTR("blank", "body");	 
?>
			<TD><a href="optionSummary.phtml?Option=Locker">Extra Locker</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD><?= display_dollar_format($row['TotalValue'] > 0 ? $row['TotalValue'] : 0); ?></TD>
		</TR>
<?
	if (!defined('PROJECT_HAS_BICYCLE_RACK') || PROJECT_HAS_BICYCLE_RACK){
	$sql = "SELECT COUNT(UserID) As TotalNumber, 
			SUM(BicycleRackCharge) As TotalValue
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND BicycleRack=1";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	
	$totalNumber += $row['TotalNumber'];
	$totalValue += $row['TotalValue'] > 0 ? $row['TotalValue'] : 0;
	displayMouseOverTR("blank", "body");	 
	
	if (!defined('PROJECT_HAS_ROOF_DECK') || PROJECT_HAS_ROOF_DECK){
	$sql = "SELECT COUNT(UserID) As TotalNumber, 
			SUM(RoofDeckCharge) As TotalValue
		FROM User 
		WHERE (User.DealStatus=\"FIRM\"
			OR User.DealStatus=\"PENDING\"
			OR User.DealStatus=\"CORPORATE\")
			AND RoofDeck=1";
		
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	
	$totalNumber += $row['TotalNumber'];
	$totalValue += $row['TotalValue'] > 0 ? $row['TotalValue'] : 0;
	displayMouseOverTR("blank", "body");	 
?>
			<TD><a href="optionSummary.phtml?Option=RoofDeck">Roof Deck</a></TD>
			<TD CLASS="blank-right"><?= $row['TotalNumber']; ?></TD>
			<TD CLASS="blank-right"><?= display_dollar_format($row['TotalValue'] > 0 ? $row['TotalValue'] : 0); ?></TD>
		</TR>
<?
	}		
?>
			<TD><a href="optionSummary.phtml?Option=BicycleRack">Bicycle Rack</a></TD>
			<TD><?= $row['TotalNumber']; ?></TD>
			<TD><?= display_dollar_format($row['TotalValue'] > 0 ? $row['TotalValue'] : 0); ?></TD>
		</TR>
<?
	}
	?>		
		<TR CLASS="tail">
			<TD>Subtotal</TD>
			<TD><?= $totalNumber; ?></TD>
			<TD><?= display_dollar_format($totalValue); ?></TD>
		</TR>
		
<?	
	
// reset totalValue var
	$totalValue = 0;
?>			
		<TR CLASS=head>
			<TD>Incentive</TD>
			<TD>#</TD>
			<TD>Total</TD>
		</TR>		

<?

//	$sql = "SELECT Package.PackageID As PackageID, Package.PackageName As PackageName, 
//			COUNT(UserPackage.Note) As TotalNumber,
//			SUM(UserPackage.Note) As TotalValue
//		FROM Package 
//			LEFT JOIN UserPackage 
//				ON Package.PackageID=UserPackage.PackageID 
//			LEFT JOIN User 
//				ON UserPackage.UserID=User.UserID 
//				AND (User.DealStatus=\"FIRM\"
//				OR User.DealStatus=\"PENDING\") 
//		GROUP BY(Package.PackageID)";



//	$sql = "SELECT Package.PackageID As PackageID, Package.PackageName As PackageName, 
//			COUNT(UserPackage.Note) As TotalNumber,
//			SUM(UserPackage.Note) As TotalValue
//		FROM Package 
//			LEFT JOIN UserPackage 
//				ON Package.PackageID=UserPackage.PackageID 
//			LEFT JOIN User 
//				ON UserPackage.UserID=User.UserID 
//		WHERE User.DealStatus=\"FIRM\" 
//		OR User.DealStatus=\"PENDING\" 
//		OR User.DealStatus=NULL
//		GROUP BY(Package.PackageID)";
//		
	$packageSql = "SELECT Package.PackageID As PackageID, Package.PackageName As PackageName
		FROM Package 
		GROUP BY (Package.PackageID)";


	$packageResult = mysql_query($packageSql) or log_err_die(mysql_error(),$PHP_SELF);

	while ($packageRow = mysql_fetch_array($packageResult))
	{

//		$sql = "SELECT Count(UserPackage.Note) As TotalNumber, SUM(UserPackage.Note) As TotalValue
//				FROM UserPackage, User
//				WHERE UserPackage.PackageID=" . $packageRow['PackageID'] . "
//				AND UserPackage.UserID=User.UserID
//				AND (User.DealStatus=\"FIRM\" 
//				OR User.DealStatus=\"PENDING\")";
				
		$sql = "SELECT Count(UserPackage.Note) As TotalNumber, SUM(UserPackage.Note) As TotalValue
				FROM UserPackage, User
				WHERE UserPackage.PackageID=" . $packageRow['PackageID'] . "
				AND UserPackage.UserID=User.UserID
				AND User.DealStatus!=\"Rescinded\"";
				
		$result= mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
		$row= mysql_fetch_array($result);

		if (is_solstice_1($PHP_SELF)){
			if ($packageRow['PackageName'] == "Commission deduct on closing"){
				$commissonDeducttPackageID = $packageRow['PackageID'];
				$commissonDeductCount = $row['TotalNumber'];
				$commissonDeductValue = $row['TotalValue'];
				continue;
			}
		}	
					
		$totalNumber += $row['TotalNumber'];
		$totalValue += $row['TotalValue'];
	displayMouseOverTR("blank", "body");	 

?>
			<TD><a href="optionSummary.phtml?PackageID=<?= $packageRow['PackageID']; ?>"><?= $packageRow['PackageName'];?></a></TD>
			<TD><?= $row['TotalNumber'];  ?></TD>
			<TD><?= display_dollar_format($row['TotalValue']); ?></TD>
		</TR>
<?
	}
?>	
		<TR CLASS="tail">
			<TD>Total</TD>
			<TD><?= $totalNumber;  ?></TD>
			<TD><?= display_dollar_format($totalValue); ?></TD>
		</TR>
<?	
		if (is_solstice_1($PHP_SELF)){			
?>		<TR CLASS=head>
			<TD>Special</TD>
			<TD>#</TD>
			<TD>Total</TD>
		</TR>
<?	displayMouseOverTR("blank", "body");	 
?>			<TD><a href="optionSummary.phtml?PackageID=<?= $commissonDeducttPackageID; ?>">Commission deduct on closing</a></TD>			
			<TD><?=	$commissonDeductCount; ?></TD>
			<TD><?= display_dollar_format($commissonDeductValue); ?></TD>
		</TR>			
<?		}	
?>					

	</TABLE>
	<H4>Unit Sales</H4>
	<TABLE>
		<TR CLASS="head">
			<TD>Type</TD>
			<TD>Sales</TD>
			<TD>Total Units</TD>
			<TD>%</TD>
			<TD>Area Sold</TD>
			<TD>Sales Price</TD>
			<TD>Sales Price/sq. ft.</TD>
			<TD>Total Unit Sales</TD>
			<TD>VTB</TD>
		</TR>
<?
	$sql = "SELECT UnitType, Count(UnitType) As TotalNoOfUnit 
			FROM Unit 
			GROUP BY UnitType";
			
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);

	$totalSales = 0;
	$totalUnit = 0;
	$totalArea = 0;
	$totalSalesPrice = 0;
	$totalNetPrice = 0;
	$netPrice = 0;

	while ($row = mysql_fetch_array($result))
	{
		$netPrice = 0;
		
		
		$sql = "SELECT SUM(Area) As Area, Count(*) As NoOfSales, SUM(User.Price) As SumOfSalesPrice, 
				SUM(User.UnitAllowance) As SumOfAllowance, SUM(User.ParkingSpaceCharge) As SumOfParkingSpaceCharge,
				SUM(User.LockerCharge) As SumOfLockerCharge, SUM(User.AdditionalCost) As SumOfAdditionalCost,
				SUM(User.VTB) As SumOfVTB
				FROM Unit, User 
				WHERE Unit.UserID = User.UserID 
				AND Unit.UserID > 0 
				AND User.AgreementDepositDate >= \"$search_date_from\" 
				AND User.AgreementDepositDate <= \"$search_date_to\" 
				AND UnitType=\"" . $row['UnitType'] . "\"
				AND (User.DealStatus=\"FIRM\" 
				OR User.DealStatus=\"PENDING\"
				OR User.DealStatus=\"CORPORATE\")";
						
				
		$sales_result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);

		$sales_row = mysql_fetch_array($sales_result);
		
		$totalSales += $sales_row['NoOfSales'];
		$totalUnit += $row['TotalNoOfUnit'];
		$totalArea += $sales_row['Area'];
		$totalSalesPrice += $sales_row['SumOfSalesPrice'];

		$netPrice = $sales_row['SumOfSalesPrice'] + $sales_row['SumOfParkingSpaceCharge'] + 
			$sales_row['SumOfLockerCharge'] + $sales_row['SumOfAdditionalCost'];
		
		$totalNetPrice += $netPrice;
		$totalVTB += $sales_row['SumOfVTB'];

	displayMouseOverTR("blank", "body");	 
?>
			<TD><?= $row['UnitType']; ?></TD>
			<TD><?= $sales_row['NoOfSales']; ?></TD>
			<TD><?= $row['TotalNoOfUnit']; ?></TD>
			<TD><?
				if ($row['TotalNoOfUnit'] > 0)
				{
					echo number_format(($sales_row['NoOfSales'] / $row['TotalNoOfUnit']) * 100, 2);
				}
				else
				{
					echo "0";
				}
			?></TD>
			<TD><?= $sales_row['Area'] != "" ? $sales_row['Area'] : 0; ?></TD>
			<TD><?= $sales_row['SumOfSalesPrice'] != "" ? display_dollar_format($sales_row['SumOfSalesPrice']) : "$0"; ?></TD>
			<TD><?
				if ($sales_row['Area'] > 0)
				{
					display_dollar_format($sales_row['SumOfSalesPrice'] / $sales_row['Area']);
				}
				else
				{
					echo "$0";
				}
			?></TD>
			<TD><?= $netPrice != "" ? display_dollar_format($netPrice) : "$0"; ?></TD>
			<TD><?= $sales_row['SumOfVTB'] != "" ? display_dollar_format($sales_row['SumOfVTB']) : "$0"; ?></TD>
		</TR>
<?
	}
?>
		<TR CLASS="tail">
			<TD>Total</TD>
			<TD><?= $totalSales; ?></TD>
			<TD><?= $totalUnit ;?></TD>
			<TD><?
				if ($totalUnit != 0)
				{
					echo number_format(($totalSales / $totalUnit) * 100, 2);
				}
				else
				{
					echo "0";
				}
			?></TD>
			<TD><?= $totalArea; ?></TD>
			<TD><?= "$" . number_format($totalSalesPrice, 0);?></TD>
			<TD><?
				if ($totalArea != 0)
				{
					echo "$" . number_format(($totalSalesPrice / $totalArea), 2);
				}
				else
				{
					echo "0";
				}			
			?></TD>
			<TD><?= "$" . number_format($totalNetPrice, 0);?></TD>
			<TD><?= "$" . number_format($totalVTB, 0);?></TD>
		</TR>
	</TABLE>
	

	<H4>Availability</H4>
<?
	$startPrice = 150000;
	$endPrice = 390000;
	$increment = 10000;
?>
	<TABLE>
		<TR CLASS="head">
			<TD>Price Range</TD>
			<TD>Number</TD>
			<TD>%</TD>
		</TR>
<?
	$sql = "SELECT COUNT(*) 
			FROM Unit LEFT JOIN User 
			ON Unit.UserID = User.UserID
			WHERE (Unit.UserID = 0 OR User.AgreementDepositDate > \"$search_date_to\")";
			
	$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
	$row = mysql_fetch_array($result);
	$total = $row[0];

 	for ($currentPrice = $startPrice; $currentPrice <= $endPrice; $currentPrice += $increment)
 	{
  		$sql = "SELECT COUNT(*)
  				FROM Unit LEFT JOIN User 
  				ON Unit.UserID = User.UserID
  				WHERE (Unit.UserID=0 OR User.AgreementDepositDate > \"$search_date_to\")
  				AND Unit.Price >= $currentPrice
  				AND Unit.Price < " . ($currentPrice + $increment);

		$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
		$row = mysql_fetch_array($result);
	displayMouseOverTR("blank", "body");	 
?>
			<TD><?= $currentPrice . "~" . ($currentPrice + $increment - 1);?></TD>
			<TD><?= $row[0]; ?></TD>
			<TD><?
			if ($total == 0)
			{
				echo "0";
			}
			else
			{
				echo number_format(($row[0] / $total) * 100, 2);
			}
			  ?></TD>
		</TR>

<?
 	}
 		// get $endPrice and above
 		$sql = "SELECT COUNT(*)
 			FROM Unit LEFT JOIN User
 			On Unit.UserID = User.UserID
 			WHERE (Unit.UserID=0 OR User.AgreementDepositDate > \"$search_date_to\")
 			AND Unit.Price >= $currentPrice";
 			
		$result = mysql_query($sql) or log_err_die(mysql_error(),$PHP_SELF);
		$row = mysql_fetch_array($result);
	displayMouseOverTR("blank", "body");	 
?>
		<TD><?= $currentPrice . " and above";?></TD>
			<TD><?= $row[0]; ?></TD>
			<TD><?
			if ($total == 0)
			{
				echo "0";
			}
			else
			{
				echo number_format(($row[0] / $total) * 100, 2);
			}
			  ?></TD>
		</TR>
		<TR CLASS="tail">
			<TD>Total</TD><TD><?= $total; ?></TD><TD></TD>
		</TR>
	</TABLE>


</BODY>
</HTML>