<?
include_once "main_include.phtml";
include "config.phtml";
include CRM_INVERT_RELATIVE_PATH . "framework/sajax/Sajax.php";

/**
 * Get reminder note section html	
 */
function getReminderNotes($salesRepID, $sortOrder = "dueDate"){
	require_once("listReminderNotes.phtml");
	return generateReminderNote($salesRepID, $sortOrder);
}

/**
 * Delete reminder note
 */
function deleteReminderNote($NoteID){
	ob_start();
	require_once("updateNoteAction.phtml");
	$result = delete($NoteID);
    ob_end_clean();
	return $result;
}


sajax_init();
//$sajax_debug_mode = 1;
sajax_export("getReminderNotes", "deleteReminderNote");
sajax_handle_client_request();


// used by sales rep to display customers and write notes.
// sales rep enter the first name and click on display
// 1st section displays all the notes the sales rep set to "remind me"
// 2nd section displays all customers, purchasers and visitors, of this sales rep
// 3rd section displays customers, purchasers and visitors, of other sales reps
check_auth(SALES);

$currSalesRepID = get_user_id();
?>

<HTML>
<? print_top_frame($PHP_SELF, CRM_INVERT_RELATIVE_PATH); ?>
	<TITLE>My Customer</TITLE>
	<H3><?= get_project_name($PHP_SELF); ?> -- Customer List</H3>

<script language="javascript">
<? sajax_show_javascript(); ?>
</script>

<script type="text/javascript" src="<?= CRM_INVERT_RELATIVE_PATH; ?>/framework/dojo/dojo.js"></script>
<script type="text/javascript">
    dojo.require("dojo.widget.DatePicker");
    dojo.require("dojo.widget.DropdownDatePicker");
</script>

<script language="javascript" src="<?= CRM_INVERT_RELATIVE_PATH; ?>/javascript/dynamicWindow.js" type="text/javascript"></script>
<? createCalendarPopupDiv(); ?>

<script language="JavaScript">
// dispaly edit note div layer 
function displayNoteEditDIV(noteID, salesRepID, customerType, customerID){
	newHTML = '<DIV class="popupDiv">';
	newHTML = newHTML + getCloseButton(1);
	newHTML = newHTML + '<IFRAME FRAMEBORDER=0 SRC="editNote.phtml?action=edit&noteID=' + noteID + '&salesRepID=' + salesRepID + '&customerType=' + customerType + '&customerID=' + customerID + '" WIDTH=640 HEIGHT=370></IFRAME>'; 
	newHTML = newHTML + '</div>';
//	alert('newHTML=' + newHTML);
	getFloatingDivNoStyle(1).innerHTML = newHTML;

	getFloatingDiv(1).position="absolute";
	getFloatingDiv(1).width="660px";	
	getFloatingDiv(1).height="380px";
	// put it at the center of browser	
	centerDIV(getFloatingDivNoStyle(1));
	// display it
	getFloatingDiv(1).visibility="visible";	
}

// dispaly edit note div layer 
function displayNoteAddDIV(salesRepID, writtenBy, customerType, customerID){
	newHTML = '<DIV class="popupDiv">';
	newHTML = newHTML + getCloseButton(1);
	newHTML = newHTML + '<IFRAME FRAMEBORDER=0 SRC="editNote.phtml?action=add&salesRepID=' + salesRepID + '&writtenBy='+ writtenBy +'&customerType=' + customerType + '&customerID=' + customerID + '" WIDTH=640 HEIGHT=370></IFRAME>'; 
	newHTML = newHTML + '</div>';
//	alert('newHTML=' + newHTML);
	getFloatingDivNoStyle(1).innerHTML = newHTML;

	getFloatingDiv(1).position="absolute";
	getFloatingDiv(1).width="660px";	
	getFloatingDiv(1).height="380px";
	// put it at the center of browser	
	centerDIV(getFloatingDivNoStyle(1));
	// display it
	getFloatingDiv(1).visibility="visible";	
}

// default sort order
var reminderNoteSectionCurrentSortOrder = 'dueDate';

/**
* This function is used to close the DIV layer after editing note,
* and refresh current page to display modified note
*/
function editNoteDone(){
	hideFloatingDiv(1);
	// must set timer to perform the call because
	// firefox doesn't allow children to access DIV element
	timerID = self.setTimeout("x_getReminderNotes(currentSalesRepID , reminderNoteSectionCurrentSortOrder, getReminderNotes_CallBack)", 1);
}

function addNoteDone(){
	hideFloatingDiv(1);
	// must set timer to perform the call because
	// firefox doesn't allow children to access DIV element
	timerID = self.setTimeout("x_getReminderNotes(currentSalesRepID , reminderNoteSectionCurrentSortOrder, getReminderNotes_CallBack)", 1);
}

function deleteNoteDone(){
	x_getReminderNotes(currentSalesRepID , reminderNoteSectionCurrentSortOrder, getReminderNotes_CallBack);
}

function sortReminderNote(sortOrder){
	reminderNoteSectionCurrentSortOrder = sortOrder;
	x_getReminderNotes(currentSalesRepID , sortOrder, getReminderNotes_CallBack);	
}

/**
* Delete a specific note
*/
function deleteNote(noteID){
	var answer = confirm('Are you sure you want to delete this note?');
	if (answer){
		x_deleteReminderNote(noteID, deleteNoteDone);
	}	
}
</script>
<BODY>
<TABLE class="tab-table">

<?
// 1.1 if first name is not set, display purchasers of all sales reps.
if (!isSet ($currSalesRepID) || $currSalesRepID == "") {
	$sql = "SELECT *, LoginUser.UserName 
												FROM User, LoginUser 
												WHERE User.SalesRepID = LoginUser.LoginUserID
												OR User.SalesRepID1 = LoginUser.LoginUserID
												ORDER BY LoginUser.LoginUserID, AgreementDepositDate DESC ";
	$result = mysql_query($sql) or log_err_die(mysql_error(), $PHP_SELF);

	$preSalesRepID = 0;
	
	while ($row = mysql_fetch_array($result)) {
		if ($preSalesRepID != $row["SalesRepID"]) {
?>


  <TR>
    <TD COLSPAN="10"><BR><BR><H4>Customers of <?= $row["UserName"]; ?></H4></TD>
  </TR>

  <TR CLASS="head">
    <TD>Customer Type</TD>
    <TD>Purchase Date</TD>
    <TD>User Name</TD>
    <TD>Suite Number</TD>
    <TD>Deal Status</TD>
  </TR>
<?


		}
		displayMouseOverTR();
?>
    <TD>Purchaser</TD>
    <TD><a href="<?= CRM_INVERT_RELATIVE_PATH ?>userListing.phtml?action=display&mode=purchaser&UserID=<?= $row['UserID']; ?>"><?= $row["AgreementDepositDate"]; ?></a></TD>    
    <TD><a href="<?= CRM_INVERT_RELATIVE_PATH ?>userListing.phtml?action=display&mode=purchaser&UserID=<?= $row['UserID']; ?>"><?= $row["UserName"] ?></a></TD>
    <TD><a href="<?= CRM_INVERT_RELATIVE_PATH ?>userListing.phtml?action=display&mode=purchaser&UserID=<?= $row['UserID']; ?>"><?= $row["UnitNumber"] ?></a></TD>
    <TD><a href="<?= CRM_INVERT_RELATIVE_PATH ?>userListing.phtml?action=display&mode=purchaser&UserID=<?= $row['UserID']; ?>"><?= $row["DealStatus"] ?></a></TD>
  </TR>
<?


		$preSalesRepID = $row["SalesRepID"];
	}
	exit;
}

// 1.2 find the sales rep with the given first name
$sql = "SELECT * FROM LoginUser WHERE LoginUserID = '$currSalesRepID'";
$result = mysql_query($sql) or log_err_die(mysql_error(), $PHP_SELF);

if (mysql_num_rows($result) == 0)
	print "<p class=\"error\">Sorry, could not find current login user.</p>";

$row = mysql_fetch_array($result);


// 2. display notes written by current sales rep with "remindMe" set to 1.

 
?>
  <INPUT TYPE="HIDDEN" NAME="firstName" VALUE="<?= $firstName ?>">
  <TR>
    <TD COLSPAN="10"><BR><BR><? createCollapsibleDIVIcon("Reminder Notes", "ReminderNotesDIV"); ?></TD>
  </TR>
  </TABLE>
  
<?


// prepare data for creating list of ContactVia
$sql_ContactVia = "SELECT ContactVia from ContactVia_list";
$result_ContactVia = mysql_query($sql_ContactVia) or log_err_die(mysql_error(), $PHP_SELF);

?>

<DIV ID="reminderSectionDIV">
</DIV>

<script language="javascript" >
function getReminderNotes_CallBack(html){
	reminderSectionDIVObj = document.getElementById("reminderSectionDIV");
	reminderSectionDIVObj.innerHTML = html;
	reminderSectionDIVObj.style.visibility="visible"; 	
}

x_getReminderNotes(<?= $currSalesRepID; ?>, getReminderNotes_CallBack);
</script>
<?

//print getReminderNotes($currSalesRepID);
// last week's sale
$sql = "SELECT CURDATE() today";
$result = mysql_query($sql) or log_err_die(mysql_error(), $PHP_SELF);
$row = mysql_fetch_array($result);
$curr_date = $row["today"];

$sql = "SELECT DATE_SUB(CURDATE(),INTERVAL 7 DAY) one_week_ago";
$result = mysql_query($sql) or log_err_die(mysql_error(), $PHP_SELF);
$row = mysql_fetch_array($result);
$one_week_ago = $row["one_week_ago"];
?>
<TABLE CELLSPACING=5>
  <TR>
    <TD><BR><BR><? createCollapsibleDIVIcon("Sales From $one_week_ago To $curr_date ", "SalesSummaryDIV"); ?></TD>
  </TR>
  </TABLE>
  
<? createCollapsibleDIV("SalesSummaryDIV"); ?>  	
	<TABLE CELLSPACING=5>
  
<?
$sql = "SELECT * FROM User 
		WHERE DealStatus !='Rescinded' 
		AND AgreementDepositDate >= '$one_week_ago'
		AND (SalesRepID = $currSalesRepID
		OR SalesRepID1 = $currSalesRepID)";
$result = mysql_query($sql) or log_err_die(mysql_error(), $PHP_SELF);

$num_of_rows = 0;

while ($row = mysql_fetch_array($result)) {
	if ($num_of_rows++ % DEFAULT_NUM_OF_ROWS_TO_DISPLAY_HEADER == 0)
	{
?>
  <TR CLASS="head">
    <TD>Customer Type</TD>
    <TD>Customer Name</TD>
    <TD>Suite Number</TD>
    <TD>Deal Status</TD>
    <TD>Purchase Date</TD>
  </TR>
<?
	}
	
	if ($class == "body" || $class == "") {
		$class = "blank";
	} else {
		$class = "body";
	}
?>

  <TR CLASS="<?= $class; ?>" onmouseover="this.className='<?= $class; ?>-highlight'" onmouseout="this.className='<?= $class; ?>'">
    <TD>Purchaser</TD>
    <TD><?= $row["FirstName"] . " " . $row["LastName"]?></TD>
    <TD><?= $row["UnitNumber"] ?></TD>
    <TD><?= $row["DealStatus"] ?></TD>
    <TD><?= $row["AgreementDepositDate"] ?></TD>
  </TR>

<?
}
?>
	</TABLE>
	</DIV>
<?
// default customer type is Purchaser
if (!isset ($CustomerType)) {
	$CustomerType = "visitor";
}
?>
	<TABLE CELLSPACING=5>
  <TR>
    <TD><BR><BR><? createCollapsibleDIVIcon("My Customers", "MyCustomersDIV"); ?></TD>
  </TR>
  </TABLE>
  
<? createCollapsibleDIV("MyCustomersDIV"); ?>  	
	<TABLE CELLSPACING=5>
  <TR>
  	<TD COLSPAN="10">
  		<DIV id="customerSearchCriteria">
			<TABLE>
				<FORM NAME="search_purchaser" METHOD="GET" TARGET="customerListFrame" ACTION="listCustomer.phtml">
				<INPUT TYPE="HIDDEN" NAME="currSalesRepID" value="<?= $currSalesRepID; ?>">
		<TR CLASS="blank">
			<TD>First Name : </TD>
			<TD><INPUT TYPE="TEXT" NAME="search_FirstName" VALUE=""></TD>
			<TD>Last Name : </TD>
			<TD><INPUT TYPE="TEXT" NAME="search_LastName" VALUE=""></TD>
		</TR>

		<TR CLASS="blank">
			<TD>Customer Type : </TD>
			<TD><SELECT NAME="search_CustomerType">
					<OPTION VALUE="all"   <? if ($CustomerType == "all") print " SELECTED ";?>>All</OPTION>
					<OPTION VALUE="user" <? if ($CustomerType == "user") print " SELECTED ";?>>Purchaser</OPTION>
					<OPTION VALUE="visitor"   <? if ($CustomerType == "visitor") print " SELECTED ";?>>Visitor</OPTION>
				</SELECT>
			</TD>
			<TD>Home Phone  : </TD>
			<TD><INPUT TYPE="TEXT" NAME="search_PhoneNumber" VALUE="<?= $search_PhoneNumber; ?>" onChange="this.value=tool.string.ReformatPhoneNumber(this.value);"></TD>
		</TR>
		<TR CLASS="blank">
			<TD>Broker Agent : </TD>
			<TD><INPUT TYPE="TEXT" NAME="search_BrokerAgentName" VALUE="<?= $search_BrokerAgentName; ?>"></TD>
			<TD>Suite Number  : </TD>
			<TD><INPUT TYPE="TEXT" NAME="search_UnitNumber" VALUE="<?= $search_UnitNumber; ?>"></TD>
		</TR>
		<TR CLASS="blank">

			<TD>Register Date From :<BR>(YYYY-MM-DD) </TD>

			<TD><? display_date("RegistrationDateFrom", "search", "", false); ?></TD>

			<TD>Register Date To :<BR>(YYYY-MM-DD) </TD>
			<TD><? display_date("RegistrationDateTo", "search", "", false); ?></TD>

		</TR>
		<TR CLASS="blank">

			<TD COLSPAN=5 ALIGN="LEFT">Note : Use % as a wildcard character</TD>
		</TR>
		<TR>
			<TD COLSPAN="5" ALIGN="LEFT" CLASS="blank">
				<INPUT TYPE="SUBMIT" VALUE="Search">					
				<INPUT TYPE="button" VALUE="List All" onClick='document.getElementById("searchCustomerListAll").submit()'>
				
				</FORM><FORM ID="searchCustomerListAll" NAME="search_purchaser" METHOD="GET" TARGET="customerListFrame" ACTION="listCustomer.phtml">
					<INPUT TYPE="HIDDEN" NAME="currSalesRepID" value="<?= $currSalesRepID; ?>">
					<INPUT TYPE="HIDDEN" NAME="listAll" value="1">
				</FORM>  				
			</TD>
		</TR>
		</TABLE>
 		 </DIV>
  	</TD>
  </TR>
  <TR width=100%>
  	<TD COLSPAN="10">
  		<DIV id="customerDIV" border-left: 1px gray solid; border-bottom: 1px gray solid; 
	           padding:0px; margin: 0px">
			<IFRAME SRC="listCustomer.phtml?search_CustomerType=visitor&currSalesRepID=<?= $currSalesRepID; ?>" name="customerListFrame" width=900 height=2500 frameborder="0"></IFRAME>
		</DIV>
	</TD>
  </TR>	
	</TABLE>
	</DIV>
  </BODY>
  <script language="javascript">
  var currentSalesRepID = <?= $currSalesRepID; ?>;  
  </script>
</HTML>
