<?php
/*
 * Created on 3-Oct-2006
 *
 * Agreemenht text includes in preview.phtml
 * This file changes between different projects
 */
?>
<table cellspacing="0" cellpadding="5" border="0" width="100%">
<tr>
<td align="center">
<font size="4">TERMS AND CONDITIONS</font>
</td>
</tr>

<tr>
<td>
<font face="Arial,Verdana,Helvetica" size="1">
<br />
<br />
<br />
<br />

<font size="2">
I / We hereby confirm that the above List of Suite Selections represent my / our final instructions to the LJM Development to include these finishes in my / our suite at Appleby, subject to the following conditions:

<BR/> <BR/>
I / We understand that the above selections are final and that I / we cannot change my selections once I / we have authorized them below.
<BR/> <BR/>

If I / we have chosen Options and Upgrades that consist of natural materials, I / we understand that natural materials are rarely consistent in colour or shade and some colour variation between the samples and the materials that are installed in my suite is possible.
<BR/> <BR/>

I / We understand that many suppliers have a continuing product improvement programme. This means that the exact selections I / we have selected above may not then be available at the time those selections would be installed in my suite. In those circumstances, I / we authorize the LJM Development to use substitute materials of a similar or superior quality.
<BR/> <BR/>
<BR/> <BR/>

Homeowner Signature: ______________________________________________________________
<BR/> <BR/> <BR/>

LJM Representative Signature:_________________________________________________________
<BR/> <BR/> <BR/>
Marlene Card <BR/>
Interior Designer <BR/>
</font>
</td>
</tr>
</table>

</td>
</tr>
</table>

