<?php
/*
 * Created on 3-Oct-2006
 *
 * Agreemenht text includes in preview.phtml
 * This file changes between different projects
 */
?>
<table cellspacing="0" cellpadding="5" border="0" width="100%">
<tr>
<td>

<font face="Arial,Verdana,Helvetica" size="1">
<br>
<br>
<br>
<br>
<br>
<font size="2">
I / We hereby confirm that the above List of Options and Upgrades represent my / our <b>final</b> instructions to the Davies Smith Developments Partnership to include these Options and Upgrades in my / our suite at  
<?= get_project_name($PHP_SELF); ?> 
, subject to the following conditions:
<br>
<br>
<ul>
<li TYPE="CIRCLE">I / We understand that <b>the above selections are final</b> and that I / we cannot change my selections once I / we have authorised them below.
<br><br>
<li TYPE="CIRCLE">I / We understand that any selections that I / we have made based upon the Images shown on this Internet based program are limited by the Internet's low graphics resolution. I / we <b>have inspected actual samples of my selections</b> at the H.O.M.E. Decor Center and satisfied my / ourselves as to their suitability.
<br><br>
<li TYPE="CIRLE">If I / we have chosen Options and Upgrades that consist of natural materials, I / we understand that <b>natural materials are rarely consistent in colour or shade</b> and some colour variation between the samples and the materials that are installed in my suite is possible. 
<br><br>
<li TYPE="CIRCLE">I / We understand that <b>many suppliers have a continuing product improvement programme.</b> This means that the exact Options or Upgrades I / we have selected above may not then be available at the time those Options or Upgrades would be installed in my suite. In those circumstances, I / we authorise the Davies Smith Developments Partnership to use substitute materials of a similar or superior quality.
</ul>
I / we hereby acknowledge that these Options and Upgrades represent a total cost of 
<nobr><b>$ <?= number_format($total_with_tax + $credit, 2)?></b></nobr> 
<b>inclusive of tax</b> and I / we hereby confirm that I / we will be responsible for this cost. I / we further acknowledge that the payment schedule for this work is as follows: 
<br>
<br>
<ul>
<li>50% of the total cost upon signature hereof.</li>
<br><br>
<li>The remainder of the total cost 120 days of the signature hereof.
</ul>
<br>
<br>
<br>
<br>
<table cellspacing="0" cellpadding="0" border="0" width="100%">
<tr>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Signed<br>
<img src="black.gif" width="400" height="1" border="0"><br>
Purchaser</font></td>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Date:<br>
<img src="black.gif" width="170" height="1" border="0"></font></td>
</tr>
<tr>
<td colspan="2"><font face="Arial,Verdana,Helvetica" size="2">&nbsp;</font></td>
</tr>
<tr>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">and<br>
<img src="black.gif" width="400" height="1" border="0"><br>
Purchaser</font></td>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Date:<br>
<img src="black.gif" width="170" height="1" border="0"></font></td>
</tr>
<tr>
<td colspan="2"><font face="Arial,Verdana,Helvetica" size="2">&nbsp;</font></td>
</tr>
<tr>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Signed<br>
<img src="black.gif" width="400" height="1" border="0"><br>
Davies Smith Developments Partnership</font></td>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Date:<br>
<img src="black.gif" width="170" height="1" border="0"></font></td>
</tr>
<tr>
<td colspan="2"><font face="Arial,Verdana,Helvetica" size="2">&nbsp;</font></td>
</tr>
<tr>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Legal documents finalised<br>
<img src="black.gif" width="400" height="1" border="0"><br>
Davies Smith Developments Partnership</font></td>
<td valign="top"><font face="Arial,Verdana,Helvetica" size="2">Date:<br>
<img src="black.gif" width="170" height="1" border="0"></font></td>
</tr>
</table>
</font>

</td>
</tr>
</table>

