<?
include "main_include.phtml";

?>
<html>
<? print_top_frame($selfPath, WEB_RESOURCE_INVERT_RELATIVE_PATH . "/", false, false); ?>

<head>
<title><?= get_project_name($PHP_SELF);?> - Login</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body text="#000000" link="#0000FF" alink="#0000FF" vlink="#0000FF" bgcolor="#FFFFFF" onLoad="setStartFocus();">
<center>
<table height="100%" width="100%">
	<tr>
		<td align="center" valign="center">
			<table cellspacing="0" cellpadding="0" border="0" wssidth="700" hsseight="10">
				<td align="left" valign="bottom"><img src="images/project-logo-small.jpg"></td>
				<td></td>
			</tr>
			<tr><td><br></td></tr>
			<tr><td colspan=5 align="right"><img src="images/orange-bar.jpg"></td></tr>
			<tr>
				<td width=230 valign="top" align="right"><img wissdth=230 src="images/project-building-side.jpg"></td>
				<td valign="top"align="left" width=470>
					<table cellspacing="0" cellpadding="0" border="0" width="100%" heissght="10">
						<tr>
							<td align="left" ><img src="images/blue-bar.jpg"></td>
						</tr>
						<tr><td><br></td></tr>
						<tr>
							<td align="center"><img width=150 src="images/home-options-logo-small.jpg"></td>
						</tr>
						<tr>
							<td colspan=5 class="blank" align="center">
								<font size=2 color="#AC6503"><i>Welcome to the<br>
								LJM Development Options and Upgrades Programme:</i></font><br><br>
								<font size=5 color="#333333">Home Options Made Easy</font><br><br>
								<font color="#AC6503"><i>Please enter the login and password you were given by your <br>
								Customer Service Representative</i></font><br>
							</td>
						</tr>
						
						<tr>
						<td colspan=2 align="center" class="blank"><br><font color="FF0000">
						<? displayError(); ?>
						</font><br></td>
						</tr>
						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr><td></td></tr>
						<form action="login.phtml" method="post" name="LoginScreen">
						
						<tr>
							<td colspan=5 align="center">
								<table>
									<tr>
										<td class="blank"><font color="#AC6503">Login:</font></td>
										<td class="blank"><font color="#8BC5D3"><input type="center" name="loginName" id="requireStartFocus" onFocus="(this.select())" size="10" maxlength="10"></font></td>						
									</tr>
									<tr>
										<td align="center" class="blank"><font color="#AC6503">Password:</font></td>
										<td><input type="password" name="password" size="10" maxlength="10"></td>
									</tr>
								</table>									
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr>
						<td colspan="2" align="center"><b><input type="submit" value="NEXT >>"></b><br>
						<br>
						<br>
						</font></td>
						</tr>	
						</form>	
								
					</table>			
				</td>				
			</tr>
			
			</table>
		</td>
	</tr>
</table>
</center>
</body>

</html>
