<?
include "main_include.phtml";
	
	$sql	= "SELECT	User.UserID AS UserID,
				FirstName,
				LastName,
				Login,
				Passwd,
				User.UnitNumber AS UnitNumber,
				Unit.UnitType AS UnitType,
				Address,
				PostalCode,
				City,
				Country,
				PhoneNumber,
				Email,
				ContractorReport,
				UserReport
			FROM User
			LEFT JOIN Unit
			ON Unit.UserID=User.UserID
			WHERE UserReport=1
			ORDER BY User.UnitNumber";

	$result = mysql_query($sql,$db) or die("Error : " . mysql_error() . " <BR>" . $sql);			
?>
<html>
<center>
<h1>Citygate</h1>
<h3>Owner Report</h3>
<table>	
<?
	while ($row = mysql_fetch_array($result))
	{
?>
	<tr>
		<td><b>First Name : </b></td>
		<td><?=$row['FirstName']?></td>				
		<td><b>Last Name : </b></td>
		<td><?=$row['LastName']?></td>		
		<td><b>Login: </b></td>	
		<td><?=$row['Login']?></td>				
	</tr>
	<tr>			
		<td><b>Unit Number: </b></td>
		<td><?=$row['UnitNumber']?></td>		
		<td><b>Unit Type: </b></td>
		<td><?=$row['UnitType']?></td>		
	</tr>
	<tr>	
		<td><b>Address:</b> </td>
		<td colspan="3"><?=$row['Address']?></td>		
		<td><b>Postal Code: </b></td>
		<td><?=$row['PostalCode']?></td>
	</tr>
	<tr>	
		<td><b>City: </b></td>
		<td><?=$row['City']?></td>		
		<td><b>Country: </b></td>
		<td><?=$row['Country']?></td>		
	</tr>
	<tr>	
		<td><b>Phone Number: </b></td>
		<td><?=$row['PhoneNumber']?></td>		
		<td><b>Email: </b></td>
		<td><?=$row['Email']?></td>		
	</tr>	
	<tr>
		<td colspan="10"><hr size=7" noshade></td>
	</tr>
<?	
	}	
?>
</table>
<table>
<tr>
<td><font face="Verdana,Arial,Helvetica" size="2"><b><br>
<br>
<a href="display_table.phtml?table_name=UnitType">Unit Types</a><br>
<a href="display_table.phtml">Options and Upgrades</a><br>
<a href="display_contractor.phtml">Contactors</a><br>
<a href="contractor_pay.phtml">Contactor Payment Totals</a></br>
<a href="disable_section.phtml">Disable Section by Unit Type</a></b></font></td>
<tr>
</table>
</center>
	
</html>