<?php
/*
 * Created on 26-Jul-2006
 * UnitNumber
 *
 */
$not_include_javascript = 1;
include_once "main_include.phtml"; 
include WEB_RESOURCE_INVERT_RELATIVE_PATH ."/" . "framework/sajax/Sajax.php";

function &getContractorRows(){
	$contractor_sql = "SELECT ContractorID, ContractorName, MarkUpPercentage 
						FROM Contractor  
						WHERE ContractorName <> ''";
	
	$contractor_result = executeSql($contractor_sql);
	return $contractor_result;
}

function &getUserSaveTableRows($UnitNumber){
	$usersave_sql = 	" SELECT UserSave.*, Section.Name AS SectionName," .
						" Subsection.Name AS SubsectionName, " .
						" Options.Name AS OptionName," .
						" Item.Name AS ItemName " .
						" FROM UserSave, Item, Options, Section, Subsection " .
						" WHERE UnitNumber=" . $UnitNumber .
						" AND UserSave.ItemID = Item.ItemID" .
						" AND UserSave.OptionID = Options.OptionID" .
						" AND Item.SubsectionID = Subsection.SubsectionID" .
						" AND Subsection.SectionID = Section.SectionID " .
						" ORDER BY Section.Name, Subsection.Name, Item.Name, Options.Name";
						
	$usersave_result = executeSql($usersave_sql);
	return $usersave_result;
}

/**
 * Print out content for the table
 */
function getContent($UnitNumber){
	ob_start();
	
?>
<TABLE>
	<TR class="head">
		<th nowrap><?= print_space(15); ?>Section<?= print_space(15); ?></th>
	
		<th>Option</th>
<?

	$contractor_result = getContractorRows();
	$numOfContractor = getNumOfContractor();
	
	for ($i=0; $contractor_row = mysql_fetch_array($contractor_result); $i++) {
			if ($i == 11 || $i == 22 || $i == 33){
?>				<TD nowrap><?= print_space(15); ?>Section<?= print_space(15); ?></TD>				
<?			}
						
		if ($contractor_row['ContractorName'] == ""){
			break;
		}
		echo "<th>".$contractor_row['ContractorName']."</th>\n";
	}	
?>	
	</TR>
<?
	$usersave_result = getUserSaveTableRows($UnitNumber); 

	while ($usersave_row = mysql_fetch_array($usersave_result)){
		displayMouseOverTR("blank", "blank", "javascript:editItem(". $UnitNumber . "," . $usersave_row['ItemID'] . "," . $usersave_row['OptionID'] . "," . $usersave_row['ChoiceID'] . ")");
?>		<TD ><?= $usersave_row['SectionName']; ?></TD>
		<TD ><?= $usersave_row['ItemName']; ?></TD>
<?		for ($i=0; $i < $numOfContractor; $i++){
			if ($i == 11 || $i == 22 || $i == 33){
?>				<TD ><?= $usersave_row['SectionName']; ?></TD>				
<?			}
?>		<TD><?= convertPriceConstantToString($usersave_row['contractor' . $i]); ?></TD>

<?		}		
?>		</TR>
<?	}?>		
</TABLE>	
<?
   $output = ob_get_contents();
   ob_end_clean();
   return $output;
}

sajax_init();
//$sajax_debug_mode = 1;
sajax_export("getContent");
sajax_handle_client_request();

?>
<html>
<? print_top_frame($PHP_SELF, SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/"); ?> 

<H3>Edit Unit Cost For Standard Options</H3>
<title>Edit Unit Cost For Standard Options</title>
<script language="javascript" src="<?= SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/";?>javascript/dynamicWindow.js" type="text/javascript"></script>
<script language="javascript" src="<?= SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/";?>javascript/dynamicWindowUtils.js" type="text/javascript"></script>

<script language="javascript">
<? sajax_show_javascript(); ?>
</script>

<script>
function editItem(unitNumber, itemID, optionID, choiceID ){
	newHTML = '<DIV class="popupDiv">';
	newHTML = newHTML + getCloseButton(1);
	newHTML = newHTML + '<IFRAME FRAMEBORDER=0 SRC="editUnitUpgradeItemCost.phtml?unitNumber=' + unitNumber + '&itemID=' + itemID + '&optionID=' + optionID + '&choiceID=' + choiceID + '" WIDTH=960 HEIGHT=500></IFRAME>'; 
	newHTML = newHTML + '</div>';
//	alert('newHTML=' + newHTML);
	getFloatingDivNoStyle(1).innerHTML = newHTML;

	getFloatingDiv(1).position="absolute";
	getFloatingDiv(1).width="1000px";	
	getFloatingDiv(1).height="500";
	// put it at the center of browser	
	centerDIV(getFloatingDivNoStyle(1));
	// display it
	getFloatingDiv(1).visibility="visible";	
	
}

/**
* This function is used to close the DIV layer after editing,
* and refresh current page to display modified content
*/
function editItemDone(){
	hideFloatingDiv(1);
	// must set timer to perform the call because
	// firefox doesn't allow children to access DIV element
	x_getContent(<?= $UnitNumber; ?>, getContent_CallBack);
}

/**
* Set new content to ContentDIV
*/
function getContent_CallBack(html){
	reminderSectionDIVObj = document.getElementById("contentDIV");
	reminderSectionDIVObj.innerHTML = html;
	reminderSectionDIVObj.style.visibility="visible"; 	
}
</script>

<table width=100%>	
	<tr><td class="html-space"><br></td></tr>
	<tr>
		<td align="center" class="smalltitle">Unit Number : <?= $UnitNumber;?></td>
	</tr>
</table>

<DIV id="noteDIV">
<input type=button value="Back to Report" onClick="window.location='unit_no_contractor.phtml?UnitNumber=<?= $UnitNumber; ?>&ShowPrice=1&mode=edit'">
<?= print_newline(2);?> 
<b>*Click the row to edit data</b><BR>
<b>*Setting a value to 0 will delete the Standard PO from the system</b>
<?= print_newline(2);?> 
</DIV>
<DIV id="contentDIV">
<?= getContent($UnitNumber); ?>
</DIV>