<?
include_once "main_include.phtml";
include_once "upgradeOptionAction.phtml";



// global var 
$commit = 1;
$gstRate = $upgradeOptionStatus['GSTRate'] > 0 	? $upgradeOptionStatus['GSTRate'] : getGSTRate();

?>
<body>
<table border=1>
	<tr>
		<td>Unit Number<t/d>
		<td>Total Sales</td>
		<td>Total Incentives</td>
		<td>Total Sales exclude tax</td>
		<td>HST</td>
		<td>Total Sales include Tax</td>
	</tr>
<?


// Start the unit loop
// Includes both sold and unsold unit
$unitSql = "SELECT * FROM Unit ORDER BY UnitNumber";
$unitResult = mysql_query($unitSql,$db) or handleError("", "SQL=$unitSql <br>Error=" . mysql_error(), SQL_ERROR, true);	
while ($unitRow = mysql_fetch_array($unitResult))
{

// Set default values
$UnitNumber 	= 0;
$total 		= 0;
$credit 	= 0;
$outstandingAmt = 0;

$userID 	= -1;
$cashPayment 	= 0;
$payByMortgage 	= 0;
$outstandingAmt = 0;

$UnitNumber = $unitRow['UnitNumber'];
$sql = "SELECT User.UserID, FirstName, LastName, CashPayment, PayByMortgage, OutstandingAmt, UnitType
		FROM Unit
		LEFT JOIN User
		ON User.UnitNumber=Unit.UnitNumber
		AND User.DealStatus IN (" . DEAL_STATUS_PURCHASE_INCLUDE_LIST . ") 
		WHERE Unit.UnitNumber = '" . $UnitNumber ."'";
$result = mysql_query($sql,$db) or handleError("", "SQL=$sql <br>Error=" . mysql_error(), SQL_ERROR, true);	

if (mysql_num_rows($result) > 0)
{
	$row = mysql_fetch_array($result);
	$userID = $row['UserID'];
	$cashPayment = $row['CashPayment'];
	$payByMortgage = $row['PayByMortgage'];
	$outstandingAmt = $row['OutstandingAmt'];
} 

?>

<?
// get the name of the current section
$sql = "SELECT Name, Description, SectionID
		FROM Section ORDER BY Name";
$section_result = mysql_query($sql,$db) or handleError("", "SQL=$sql <br>Error=" . mysql_error(), SQL_ERROR, true);	

while ($section_row = mysql_fetch_array($section_result))
{
	if (section_disabled($UnitType, $section_row['SectionID']))
		continue;
	else
		$sectionID = $section_row['SectionID'];
		
	// cache the html code for section, subsection title. The code
	// will be printed if item-option is available
	$htmlCacheHeader = "<tr><td colspan=\"4\" ><font size=\"4\"><b>&nbsp;<br>&nbsp;<br>" . $section_row['Name'] . "</b></font></td></tr>";

	$sql = "SELECT Name, Description, SubsectionID
			FROM Subsection
			WHERE SectionID = '$sectionID' ORDER BY Name";
	$subsection_result = mysql_query($sql,$db) or handleError("", "SQL=$sql <br>Error=" . mysql_error(), SQL_ERROR, true);	
	while ($subsection_row = mysql_fetch_array($subsection_result))
	{
		$subsectionID = $subsection_row['SubsectionID'];
		

		// Since UserSave table may not have the options if user
		// has not saved the options they choose, so standard will
		// be display if no optionID in UserSave table. 
		$sql = "SELECT Item.ItemID AS ItemID, Item.Name AS ItemName,
				Options.Name AS OptionsName, Options.Choice AS OptionsChoice,
				Choice.Name AS ChoiceName, UserSave.Price AS Price
				FROM Item
				LEFT JOIN UserSave 
				ON Item.ItemID = UserSave.ItemID
				AND UserSave.UnitNumber = '$UnitNumber'
				LEFT JOIN Options 
				ON UserSave.OptionID = Options.OptionID
				LEFT JOIN Choice
				ON UserSave.ChoiceID = Choice.ChoiceID
				WHERE Item.SubsectionID = $subsectionID
				ORDER BY Item.Name, Options.Name, Choice.Name";

		$userSave_result = mysql_query($sql,$db) or handleError("", "SQL=$sql <br>Error=" . mysql_error(), SQL_ERROR, true);	
		while ($userSave_row = mysql_fetch_array($userSave_result))
		{
			$ItemID = $userSave_row['ItemID'];
			// Check all the options for ItemName is -9999 or not. 
			// If all of the price in the options are -9999, don't show this item
/*			No need to show all the options details for summary

			// get all options for this item first, then check the price for the options
			$sql_Option = "SELECT Options.OptionID, Name FROM Item_Options, Options " .
							"WHERE ItemID=$ItemID " .
							"AND Item_Options.OptionID = Options.OptionID" 
							;
			$result_Option = mysql_query($sql_Option,$db) or handleError("", "SQL=$sql <br>Error=" . mysql_error(), SQL_ERROR, true);	
			// init the flag to be false
			$show = "false";
			// check all the prices of the options, if all of them are not OPTION_IS_NOT_UNAVAILABLE, 
			// set show to be "true", which means show the item

			while ($row_Option = mysql_fetch_array($result_Option))
			{
				$OptionID = $row_Option['OptionID'];
				$sql_Price = "SELECT Price.Price as Price 
							FROM Price
							WHERE ItemID = $ItemID
							AND OptionID = $OptionID
							AND UnitType = '$UnitType'";

				$result_Price = mysql_query($sql_Price,$db) or handleError("", "SQL=$sql_Price <br>Error=" . mysql_error(), SQL_ERROR, true);	
				$row_Price = mysql_fetch_array($result_Price);
				if ($row_Price['Price'] != OPTION_IS_NOT_AVAILABLE)
				{
					$show = "true";
				}
			} // end of row_Option while
*/


			// if show equals to false, don't show this item, and continue the loop
			if ($show == "false")
			{
				continue;
			}
			
			// if user saved option name is not required, do not display this item
			if (trim($userSave_row['OptionsName']) == OPTION_IS_NOT_REQUIRED ){
				continue;
			}
			
	
			if ($userSave_row['Price'] == "" || $userSave_row['Price'] == 0)
			{ 
				// do nothing or print NA on screen
				$a = 1;
			}
			else {
				if ($userSave_row['Price'] != OPTION_IS_NOT_AVAILABLE
					&& $userSave_row['Price'] != OPTION_IS_A_STANDARD
					&& $userSave_row['Price'] != OPTION_IS_INCENTIVE)
				{		
					if ($userSave_row['Price'] > 0){		
	//print ("UnitNumber=$UnitNumber total=$total price=" . $userSave_row['Price']);
						$total += $userSave_row['Price'];
					} else {
	//print ("UnitNumber=$UnitNumber credit=$credit price=" . $userSave_row['Price']);
						$credit += $userSave_row['Price'];	
					}
				}
			}

			//$userSave_row['OptionsName'] $userSave_row['OptionsChoice'] $userSave_row['ChoiceName']<br>";
		}// end of userSave loop
	}// end of subsection loop
}// end of section loop
	
$sql = "SELECT Description, Price
		FROM UserOption
		WHERE UnitNumber = '$UnitNumber'";
$useroption_result = mysql_query($sql,$db) or handleError("", "SQL=$sql <br>Error=" . mysql_error(), SQL_ERROR, true);	
$numOfAddChange = 0;

if (mysql_num_rows($useroption_result) > 0)
{
	for ($i=0;$useroption_row = mysql_fetch_array($useroption_result);$i++)
	{
		if ($useroption_row['Price'] < 0){
			$credit += $useroption_row['Price'];
		}
		else{
			$total += $useroption_row['Price'];
		}
	} // end of useroption loop
	$numOfAddChange = $i;
	
}

$total_sales = $total + $credit;
$gstAmount = $total_sales * $gstRate;
$total_with_tax = $total_sales + $gstAmount;


if ( $total_sales < 0 ) // Don't tax -ve values
{
	$gstAmount = 0;
	$total_with_tax = $total_sales;
}

$projectTotal += $total;
$projectTotalGST += $gstAmount;
$projectTotalCredit += $credit;
$projectTotalSales += $total_sales;

$outstandingAmt_to_display = $total_with_tax;// - $cashPayment - $payByMortgage;

$projectTotalOutstandingAmt += $outstandingAmt_to_display;
$projectTotalOutAmtWithTax = $projectTotalOutstandingAmt - $projectTotalCredit;

?>
	<tr>
		<td><?= $UnitNumber; ?></td>
		<td><?= number_format($total, 2)?></td>
		<td><?= number_format($credit, 2)?></td>
		<td><?= number_format($total_sales, 2)?></td>
		<td><?= number_format($gstAmount, 2)?></td>
		<td><?= number_format($outstandingAmt_to_display, 2)?></td>
	</tr>
<?
	}


?>
	<tr>
		<td>Total</td>
		<td><?= number_format($projectTotal, 2)?></td>
		<td><?= number_format($projectTotalCredit, 2)?></td>
		<td><?= number_format($projectTotalSales, 2)?></td>
		<td><?= number_format($projectTotalGST, 2)?></td>
		<td><?= number_format($projectTotalOutstandingAmt, 2)?></td>
		<td></td>
	</tr>

</table>
