<?php
/*
 * Created on 12-Mar-2006
 * 
 * List POs by specifying search criteria
 * $printMode : txt, HTML(default)
 * $showDefaultCol : 1/0 
 */

$not_include_javascript = 1;
include_once "main_include.phtml";
include_once SUB_FOLDER_INVERT_RELATIVE_PATH . "/" . HOME_OPTIONS_INVERT_RELATIVE_PATH . "/guiUtil.phtml";
include_once "PO/POAction.phtml";
include_once "PO/POListAction.phtml";
include WEB_RESOURCE_INVERT_RELATIVE_PATH . "/framework/URL/MultiPageNavigation.phtml";

check_auth(ADMIN);

$ShowPrice = 1;
if (!isset($MultiPageNavigationResultsPerPage) || $MultiPageNavigationResultsPerPage == ""){
	$MultiPageNavigationResultsPerPage = 100;
}

 
$action = "edit";
if (!isset($floorFrom) || $floorFrom == ""){
	$floorFrom = REAL_ESTATE_LOWEST_FLOOR;	
}
if (!isset($floorTo) || $floorTo == ""){
	$floorTo = REAL_ESTATE_HIGHEST_FLOOR;	
}
if (!isset($POView) || $POView == ""){
	$POView = "unit;rooms;trade";//trade;unit;rooms";
}

if ($showDefaultCol == 1){
	$_REQUEST[showInvoiced] = 1;
	$_REQUEST[showIssued] = 1;
	$_REQUEST[showIssuedDate] = 1;
	$_REQUEST[showPOIssuedNumber] = 1;
	$_REQUEST[showPONumber] = 1;
	$_REQUEST[showSection] = 1;
	$_REQUEST[showSubsection] = 1;
	$_REQUEST[showOption] = 1;
	$_REQUEST[showChoice] = 1;
	$_REQUEST[showCost] = 1;
}
			
$unionSQL = getPOSql($displayPOType);

if ($POView == "trade;unit;rooms"){
	$unionSQL .= "ORDER BY ContractorID, UnitNumber, SectionID, SubsectionID, ItemID";
} else if ($POView == "trade;option;choice") {
	$unionSQL .= "ORDER BY ContractorID, ItemID, OptionID, ChoiceID, UnitNumber, SubsectionID";		
} else {
	$unionSQL .= "ORDER BY UnitNumber, ContractorID, SectionID, SubsectionID, ItemID";	
}

if (!isset($MultiPageNavigationResultsPerPage) || $MultiPageNavigationResultsPerPage == ""){
	$MultiPageNavigationResultsPerPage = 100;
}		


if ($printMode == "PDF"){
	include_once ("PO/POInPdfFormat.phtml");
	include_once SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/framework/PDF/PDFMaker.phtml";
	include_once SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/framework/PDF/PDFMakerA4Config.phtml";
	
	$poFormatter = new POListPdfFormat($unionSQL, 0, $markRevised != "" ? 1 : 0);
} else {
	include_once ("PO/POInHtmlFormat.phtml");
	$poFormatter = new POListHtmlFormat($unionSQL, $_SERVER['PHPSELF'] . "?1=1&" . getQueryString());
	$multiPageNavigation = &$poFormatter->multiPageNavigation;
	
}	


////print "sql=$unionSQL<BR>";
//$price_result = mysql_query($pageSql,$db) or 
//					 die("Insert/update failed:\n" . mysql_error() . "\nFull SQL:<BR>" . $unionSQL . $PHP_SELF);
//


// generate non standard po edit button
function printNonStandardPOEditButton($POID){
?> <INPUT TYPE="BUTTON" VALUE="EDIT" ONCLICK="displayNonStandardPODIV('edit', <?= $POID; ?>)"><?	
}

function printNonStandardPODeleteButton($POID){
?> <INPUT TYPE="BUTTON" VALUE="Delete" ONCLICK="deleteNonStandardPO(<?= $POID; ?>)"><?	
}

function printNonStandardPOAddButton($POID){
?> <INPUT TYPE="BUTTON" VALUE="Add Non-Standard PO" ONCLICK="displayNonStandardPODIV('add', 0)"><?	
}

// only display the specific format, then die immediately
// in order to avoid the html search criteria
if ($printMode == "PDF"){
	// mark the po to be issued
	print $poFormatter->printPO($price_result, $POView);
	die();	
}

/**
 * Takes unlimited number of arguments
 * Arguments: inputName, displayName, value, source=_REQUEST, or DB
 */
function displayCheckBoxLocal($arguments){
	$inputName 		= $arguments['inputName'];
	$displayName	= $arguments['displayName'];
	$value 			= $arguments['value'];
	$source 		= $arguments['source'];
	
	$code = "<input type=checkbox name=\"$inputName\"";
	if ($source == "_REQUEST"){	
		if ($_REQUEST[$inputName] == $value){
			$code .=" CHECKED ";	
		}
	}
	$code .= " value=\"$value\">$displayName";
	
	return $code;
}			
?>
<html>
<DIV class="html-space">
	<br> 
</DIV>	
	<centre><H3><?= get_project_name($PHP_SELF); ?> - PO List</H3></centre>
	<script language="javascript" src="<?= WEB_RESOURCE_INVERT_RELATIVE_PATH; ?>/javascript/dynamicWindow.js" type="text/javascript"></script>
	<script language="javascript" src="<?= WEB_RESOURCE_INVERT_RELATIVE_PATH; ?>/javascript/checkboxSelection.js" type="text/javascript"></script>
	<script type="text/javascript" src="<?= WEB_RESOURCE_INVERT_RELATIVE_PATH; ?>/framework/dojo/dojo.js"></script>

	<script>
		// generate invoice for currently displayed POs
		function issuedPOAndGeneratePOPDF(){
			var result = confirm("Issue PO will overwrite data of previously issued PO. Are you sure you want to proceed?");
			if (result == true){
				var generatePOInvoiceURL = 'PO/issuePO.phtml?issuePO=1<?= getQueryString(); ?>';
				window.location = generatePOInvoiceURL ;
			} 
		} // issuedPOAndGeneratePOPDF
		
		function generatePOPDF(){
			var generatePOInvoiceURL = '<?= $_SERVER['PHP_SELF'];?>?printMode=PDF<?= getQueryString(); ?>';
			window.open(generatePOInvoiceURL, "PDF_WIN");								
		} // generatePOPDF
		
		function selectAction_onChange() {
			var selectAction = document.getElementById("selectAction");
			var act = selectAction.options[selectAction.selectedIndex].value;
			
			if(act=="markInvoiced_yes") {
				markInvoiced("Yes");
			} else if (act=="markInvoiced_no") {
				markInvoiced('No');
			}			
   		}
   		
   		/**
   		* Reset select check box
   		*/
   		function resetSelectCheckBox(){
			var selectAction = document.getElementById("selectAction");
			selectAction.selectedIndex = 0;   		
   		}
   	
		
		function markInvoiced(yesOrNo){
//			var formObj = document.getElementById('actionForm');
//			formObj.submit();
		  dojo.io.bind({
		  	url: "PO/POSelectionAction.phtml",
		    formNode: document.getElementById('actionForm'),
		    content: {act:'markInvoiced', invoiced: yesOrNo},
		    method: "POST",
		    mimetype: "text/plain",
		    load: markInvoiced_Callback,
		    error: function(type, error){alert(error.message);}
		  });
			
		} // markInvoiced

  	function markInvoiced_Callback(type, data){
		  alert(data);
		  
		  // if update successfully, it will return message: Total xxx POs have been marked invoiced(not invoiced)
		  if(data.indexOf("Total") >= 0) {
			  var invoiced =data.indexOf("not invoiced")<0?"Yes":"No";
			  
		  	// check if invoiced was displayed
		  	var displayInvoiced = false;
		  	var tbl = document.getElementById("POListTable");
		  	for(var i=0; i<10 && i<tbl.rows.length; i++) {
		  		if(tbl.rows[i].cells[0].innerHTML == "Selection" && tbl.rows[i].cells[1].innerHTML == "Invoiced") {
		  				displayInvoiced = true;
		  				break;
		  		}
		  	}

			  // change invoiced to Yes for selected rows
			  if(displayInvoiced) {
			  	var rows = tbl.rows;
			  	for(var i=0; i<rows.length; i++) {
			  		var cell = rows[i].cells[0];
			  		// don't update DUMMY-CHECKBOX since it's only a control 
			  		// for the real checkboxes
			  		if(	cell.innerHTML.toLowerCase().indexOf("<input")>=0 &&
			  			cell.innerHTML.toLowerCase().indexOf('dummy-checkbox') < 0){
			  			for (var x=0; x<cell.childNodes.length; x++){
//				  			alert('cell.childNodes['+x+'].nodeName=' + cell.childNodes[x].nodeName);
				  		 	if (cell.childNodes[x].nodeName.toLowerCase() == "input" && cell.childNodes[x].checked) {
				  				rows[i].cells[1].innerHTML = invoiced;
				  			}
				  		}
			  		}																																																																							
			  	}																					
			  } 															
		  }
		  
		resetSelectCheckBox();				  
	}		
	</script>

<? print_top_frame($PHP_SELF, SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/");
?>
<DIV id="search" name="search">
<?
// create calendar popup div object
createCalendarPopupDiv();
createCollapsibleDIVIcon("Search Criteria", "SearchCriteriaDIV");
createCollapsibleDIV("SearchCriteriaDIV"); 
?>
	<table>
		<form id="searchForm" method=get action=<?= $_SERVER['PHP_SELF']; ?>>
<!--		<tr>
			<td>Include Floor From</td>
			<td><? display_floor_list("floorFrom", $floorFrom); ?></td>
			<td>Include Floor To</td>
			<td><? display_floor_list("floorTo", $floorTo); ?></td>
		</tr>
-->		<tr>
			<td>Include Floor (e.g. 2,4,3-9)</td>
			<td><input type="text" name="floor" value="<?= $floor ?>"></td>
			<td>Unit</td>
			<td><input type="text" name="unitNumber" value="<?= $unitNumber ?>"></td>
		<tr>
			<td>Trade</td>
			<td ><? display_contractor_list_no_DB("trade", $trade); ?></td>
		</tr>
		<tr>
			<td>Create Date From</td>
			<td><? display_date("createDateFrom", "", "", "", false, $createDateFrom); ?></td>
			<td>Create Date To</td>
			<td><? display_date("createDateTo", "", "", "", false, $createDateTo); ?></td>
		</tr>		
		<tr>
			<td>PO Issued Date From</td>
			<td><? display_date("poIssuedDateFrom", "", "", "", false, $poIssuedDateFrom); ?></td>
			<td>PO Issued Date To</td>
			<td><? display_date("poIssuedDateTo", "", "", "", false, $poIssuedDateTo); ?></td>
		</tr>		
		<tr>
			<td>PO Issued #</td>
			<td><input type="text" name="POIssuedID" value="<?= $POIssuedID?>"></td>
			<td>PO #<BR>(e.g. 205-4,205-7)</td>
			<td><input type="text" name="PONumber" value="<?= $PONumber?>"></td>
		</tr>
		<tr>
			<td>PO Status</td>
			<td><? display_PO_issued_list("displayIssuedPO", $displayIssuedPO); ?></td>
			<td>PO Type</td>
			<td><? display_PO_type_list("displayPOType", $displayPOType); ?></td>
		</tr>
		<tr>
			<td>Display only Non-Zero Cost PO </td>
			<td><input type="CHECKBOX" NAME="POZeroCostFiltration" VALUE="Yes" <?= $POZeroCostFiltration != "" ? " CHECKED " : ""; ?></td>
			<td>Mark as Invoiced</td>
			<td>
				<SELECT name="markInvoiced"">
					<OPTION VALUE="All" <?= $markInvoiced=="All" ? "selected=\"selected\"" : ""; ?>>All
					<OPTION VALUE="Yes" <?= $markInvoiced=="Yes" ? "selected=\"selected\"" : ""; ?>>Yes
					<OPTION VALUE="No"  <?= $markInvoiced=="No"  ? "selected=\"selected\"" : ""; ?>>No
				</SELECT>
			</td>
		</tr>
		<tr>
			<td>PO View</td>
			<td><? display_PO_view_list("POView", $POView); ?></td>
			<td># of PO Per Page</td>
			<td><?= $multiPageNavigation->getRowsPerPageComboBox(); ?></td>
		</tr>
		<tr>
			<td>Mark REVISED in PDF</td>
			<td><input type="CHECKBOX" NAME="markRevised" VALUE="1" <?= $markRevised != "" ? " CHECKED " : ""; ?></td>
		</tr>
		<tr>
			<td>Select column to display</td>
		</tr>
		<tr>
			<td colspan=100>
			<?= displayCheckBoxLocal(array(inputName=>"showSelection", displayName=>"Selection", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showInvoiced", displayName=>"Invoiced", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showIssued", displayName=>"Issued", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showIssuedDate", displayName=>"Issued Date", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showPOIssuedNumber", displayName=>"PO Issued #", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showPONumber", displayName=>"PO #", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showSection", displayName=>"Section", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showSubsection", displayName=>"Subsection", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showOption", displayName=>"Option", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showChoice", displayName=>"Choice", value=>1, source=>"_REQUEST")); ?>
			<?= displayCheckBoxLocal(array(inputName=>"showCost", displayName=>"Cost", value=>1, source=>"_REQUEST")); ?>
			</td>
		</tr>
		<tr>
			<td><input type="submit" value="Search"></td>
		</tr>
		<tr>
			<td colspan=100><input type="button" value="Issue PO and Generate PO PDF" onClick="issuedPOAndGeneratePOPDF()">
			<input type="button" value="Download Issued PO PDF" onClick="generatePOPDF()"<?
			if (!isset($POIssuedID) || $POIssuedID == ""){
				print " DISABLED ";	
			}
			?>></td>
		</tr>
		</form>
		<form id="actionForm" method="get" action="updatePO.phtml">
		<tr>
			<td>
				<SELECT id="selectAction" onChange="selectAction_onChange()">
					<OPTION VALUE="">Choose Selection actions ...
					<OPTION VALUE="markInvoiced_yes">&nbsp;&nbsp;&nbsp; Mark as Invoiced
					<OPTION VALUE="markInvoiced_no" >&nbsp;&nbsp;&nbsp; Mark as Not Invoiced
				</SELECT>
			</td>
			<!--
			<td><input type="button" value="Mark Selected as Invoiced" onClick="markInvoiced('Yes')"></td>
			<td><input type="button" value="Mark Selected as Not Invoiced" onClick="markInvoiced('No')"></td>
			-->
		</tr>
		
	</table>
</div>
</DIV>
<?
print $poFormatter->printPO($POView);
?>		
	</form>	
</html>