<?

include "../admin/main_include.phtml";


print_top_frame($PHP_SELF, SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/");

// This script creates 4 PDI reports: Suite Report; Floor Report; Trade Unit Report; Trade Floor Report

// Handle update request on PDIDefect -> TradeContacted
if ($update) {
        // ALLEN Only update the one being unchecked
        //$sql = "UPDATE PDIDefect SET TradeContacted=0";
        //$result = mysql_query($sql,$db) or die("Error : $sql<br>" . mysql_error());

        // Add a hidden value in before CheckBox to let HTML code to send false value even
        // checkbox is not checked
        foreach ($_POST as $key=>$value) {
                $updateValue = 0;

                $data = explode("_", $key);
                if ($data[0] == 'TradeContacted') {
                    //print ("key=" . $key . " value=" . $value);
                        if ($value == "on") {
                            $updateValue = 1;
                        } 
                        $PDIDefect_id = $data[1];
                        $sql = "UPDATE PDIDefect SET TradeContacted=" . $updateValue . " WHERE PDIDefectID=".$PDIDefect_id;
                        $result = mysql_query($sql,$db) or die("Error : $sql<br>" . mysql_error());
                }
        }
}


// Search Feature
if (!isSet($listall)) // if not list all records, use the search criteria to do the search
{
        $values			= $_GET;
        $searchCriteria 	= "";
	$sqlCond 		= "";
        $hasSearchValue 	= false;
        //loop that adds the field names and values
        foreach($values as $key=>$val)
        {
		$search_field 	= $key;

                $pos = strpos($key, "_");
                if ($pos > 0)
                {
                        if ($val != "")
                        {
                                $hasSearchValue = true;
                                $search_field = substr($key, $pos + 1);
			}
		}

		if ($search_field == "UnitNumber") {
			//$sqlCond .= " AND UnitNumber=$val";	
			$sqlCond .= " AND (" . expandSearchCriteria(array("columnName"=>"UnitNumber", "csvValue"=>$val)) . ") ";
		}

		if ($search_field == "ContractorID") {
			if ($val != "0") {
				$sqlCond .= " AND ContractorID='$val'";
			}
		}

		$searchCriteria .= "&" . $key . "=" . $val;
	}
}

        $PDISql = "SELECT * FROM
                                (SELECT *,
                                        (CASE   WHEN DefectType = 'QA'          THEN QAReportDate
                                                        WHEN DefectType = 'PDI'         THEN PDIReportDate
                                                        WHEN DefectType = 'DAY30'       THEN day30ReportDate
                                                        WHEN DefectType = 'MONTH11'     THEN month11ReportDate
                                        END) As ReportDate,
                                        (CASE   WHEN DefectType = 'QA'          THEN QAFixedDate
                                                        WHEN DefectType = 'PDI'         THEN PDIFixedDate
                                                        WHEN DefectType = 'DAY30'       THEN day30FixedDate
                                                        WHEN DefectType = 'MONTH11'     THEN month11FixedDate
                                        END) As FixedDate
                                        FROM
                                        (SELECT PDIDefect.*, PDIType.Name as DefectName, Section.Name as SectionName, Contractor.ContractorName,
                                                (CASE   WHEN (PDIDefect.PDIDefect = 1 and PDIDefect.PDIFixed != 1) THEN 'PDI'
                                                     WHEN (PDIDefect.day30Defect = 1 and PDIDefect.day30Fixed != 1) THEN 'DAY30'
                                                     WHEN (PDIDefect.QADefect = 1 and PDIDefect.QAFixed != 1) THEN 'QA'
                                                     WHEN (PDIDefect.month11Defect = 1 and PDIDefect.month11Fixed != 1) THEN 'MONTH11'
                                                     END) AS DefectType
                                        FROM PDIDefect
                                        LEFT JOIN Section
                                        ON PDIDefect.SectionID = Section.SectionID
                                        LEFT JOIN Contractor
                                        ON PDIDefect.ContractorID = Contractor.ContractorID
                                        LEFT JOIN PDIType
                                        ON PDIDefect.PDITypeID  = PDIType.PDITypeID
                                        WHERE ((PDIDefect.PDIDefect = 1 and PDIDefect.PDIFixed != 1)
                                        OR (PDIDefect.day30Defect = 1 and PDIDefect.day30Fixed != 1)
                                        OR (PDIDefect.QADefect = 1 and PDIDefect.QAFixed != 1)
                                        OR (PDIDefect.month11Defect = 1 and PDIDefect.month11Fixed != 1))
                                         ) A
                                ) B ";

	$PDISql .= " WHERE 1=1 ";
	$PDISql .= $sqlCond;
	
	$PDISql .= " ORDER BY B.UnitNumber,  B.SectionName, B.ReportDate";

	//die("PDISql=$PDISql");
?>

<html>

<head>
  <title>PDI reports</title>
  <META http-equiv="Content-Style-Type" content="text/css">
  <link rel="stylesheet" href="./citygate.css" type="text/css">
  <link rel="stylesheet" href="<?= SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/";?>framework/JQuery/ui/1.9.2/themes/base/jquery-ui.css" />
  <script src="<?= SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/";?>framework/JQuery/jquery-1.8.3.js"></script>
  <script src="<?= SUB_FOLDER_INVERT_RELATIVE_PATH."/".HOME_OPTIONS_INVERT_RELATIVE_PATH."/";?>framework/JQuery/ui/1.9.2/jquery-ui.js"></script>
  <script src="report_pdi_others.js"></script>
</head>

<body text="#000000" link="#0000FF" alink="#0000FF" vlink="#0000FF" bgcolor="#FFFFFF">

<BR><BR>
                <DIV id="search" name="search">
<?
createCollapsibleDIVIcon("Search Criteria", "SearchCriteriaDIV");
createCollapsibleDIV("SearchCriteriaDIV");
?>
        <FORM NAME="search_purchaser" METHOD="GET" ACTION="<?= $PHP_SELF; ?>">
                <TABLE>
                <INPUT TYPE="HIDDEN" NAME="orderby" VALUE="<?= $orderby;?>">

                <TR CLASS="blank">
                        <TD>Suite Number: <BR>e.g. PH%, 100-120,127,129</TD>
                        <TD><INPUT TYPE="TEXT" NAME="search_UnitNumber" VALUE="<?= $search_UnitNumber; ?>"></TD>
			<TD>Trade</TD>
			<TD>                <select name="search_ContractorID" onChange="change_link('trade_unit')">
                    <OPTION VALUE="0">All</OPTION>
<?
                // listed all contractor names in dropdown listbox
		// all the available contractors, prepared for the listbox of contractors
		$sql_Contractor = "SELECT ContractorID, ContractorName FROM Contractor
				WHERE ContractorName != ''
				ORDER BY ContractorName";
		$result_Contractor = mysql_query($sql_Contractor,$db) or die("Error : $sql_Contractor<br>" . mysql_error());
                mysql_data_seek($result_Contractor, 0);
                while ($row_Contractor = mysql_fetch_array($result_Contractor))
                {
?>
                    <OPTION VALUE="<?= $row_Contractor['ContractorID'] ?>" <?
			if ($row_Contractor['ContractorID'] == $search_ContractorID) {
				echo " SELECTED ";
			}
			?>><?= $row_Contractor['ContractorName']?> </OPTION>
<?
                }
?>
			 </TD>
                </TR>
		<TR><TD><BR></TD</TR>
		<TR>
                        <TD COLSPAN="5" ALIGN="LEFT" CLASS="blank">
				<INPUT TYPE="SUBMIT" VALUE="Search">
			</TD>
		</TR>
		</TABLE>
	</FORM>
	</DIV>




  <form name="form_PDIdefectByFloor" method="post" action="<?echo  $_SERVER["PHP_SELF"] . '?search_Floor=' . $search_Floor . '&search_ContractorID=' . $search_ContractorID . '&search_UnitNumber=' . $search_UnitNumber ; ?>">
  <table cellspacing="0" cellpadding="5" border="1" width="800" style="margin-top: 1em">
<?

//
// Floor report: Report of All Defects on the XXth Floor or Floor == "all"
//

// If search_Floor is not set, then set to "all"
if (!isset($search_Floor)) {
	$search_Floor = "all";
}

?>
    <tr>
      <td class="tail" colspan="8">
        <b>All Defects on Floor  <?= $floor ?></b><br><br>
      </td>
    </tr>

<? 
	// Extract PDI Result
        $PDIresult = mysql_query($PDISql,$db) or die("Error : $PDISql<br>" . mysql_error());
        if (mysql_num_rows($PDIresult) == 0)
        {
?>
    <tr>
      <td class="head">
        No defect data found on the floor <?= $search_Floor ?>.
      </td>
    </tr>

<?
        }
        else
        {
                // table header
                echo "<input type='hidden' value='".$search_Floor."' name='search_Floor'>";
                echo "<tr>\n";
                echo "  <td align='center' class='head'>Unit</td>\n";
                echo "  <td align='center' class='head'>Defect Description</td>\n";
                echo "  <td align='center' class='head'>Defect Type</td>\n";
                echo "  <td align='center' class='head'>Room</td>";
                echo "  <td align='center' class='head'>Trade Assigned</td>\n";
                echo "  <td align='center' class='head' nowrap>Report Date</td>\n";
                echo "  <td align='center' class='head'>Schedule Fix Date</td>\n";

                echo "  <td align='center' class='head'>Trade Contacted &nbsp; <input type='checkbox' id='TradeContactedAll' />\n";
                echo "</tr>\n\n";


                $curr_unit = 0;
                while ($row = mysql_fetch_array($PDIresult))
                {
                        if (substr($row["UnitNumber"], 0, strlen($row["UnitNumber"]) - 2) == $search_Floor || $search_Floor == "all")
                        {
                                // print a blank line to stand out different unit
                                if ($curr_unit == 0)
                                        $curr_unit = $row["UnitNumber"];
                                elseif ($curr_unit != $row["UnitNumber"])
                                {
                                        echo "<tr><td colspan='8'>&nbsp;</td></tr>\n\n";
                                        $curr_unit = $row["UnitNumber"];
                                }

                                echo "<tr class='table_rec'>\n";
                                echo "  <td>" . $row["UnitNumber"] . "</td>\n";
                                echo "  <td>" . $row["DefectName"] . "</td>\n";
                                echo "  <td>" . $row["DefectType"] . "</td>\n";
                                echo "  <td>" . $row["SectionName"] . "</td>\n";
                                echo "  <td>" . $row["ContractorName"] . "</td>\n";
                                echo "  <td>" . $row["ReportDate"] . "</td>\n";
                                echo "  <td>" . $row["FixedDate"] . "</td>\n";
                                echo " <input type='hidden' name='TradeContacted_" . $row["PDIDefectID"] . "' value='false'>";

                                echo "  <td align='center'><input type='checkbox' name='TradeContacted_" . $row["PDIDefectID"] . "'";
                                if ($row['TradeContacted']) { echo " checked='checked'"; }
                                echo "></td>\n";
                                echo "</tr>\n\n";
                        }
                }
                echo "<tr><td colspan='5'>\n";
                echo "  <input type='submit' value='Update' name='update' size='50' style='margin-right:1em'>";
                echo "  <input type='submit' value='Cancel' name='cancel' size='50'>";
                echo "</td></tr>\n";
                echo "</form>";
        }

?>
 </table>
</body>

</html>
