<?php
/*
 * Created on 27-Dec-2006
 *
 * The calling script should initialize sajax. This script only export the necessary function to ajax
 * Action script for addtional purchaser
 */
 
include_once "config/config.phtml";
include_once "framework/sajax/Sajax.php";
include_once "guiUtil.phtml";
include_once "Entity/Controller/AddressAction.phtml";
require_once "Entity/View/AdditionalPurchaserView.phtml";


function getNewAdditionalPurchaserHTMLForm($index){
	$additionalPurchaser = new AdditionalPurchaserView();
	return $additionalPurchaser->getNewHTMLForm($index);
}

function getExistingAdditionalPurchaserHTMLForm($index, $DBResultRow, $mode = "display"){
	$additionalPurchaser = new AdditionalPurchaserView();
	return $additionalPurchaser->getExistingHTMLForm($index, $DBResultRow, $mode);
}


// should be initialized by caller
//sajax_init();
//$sajax_debug_mode = 1;
sajax_export("getNewAdditionalPurchaserHTMLForm");
// should be handled by caller
//sajax_handle_client_request();
//
//<html>
//<body>
//<form>
//<?= getNewAdditionalPurchaserHTMLForm(1);
//</form>
//</body>
//</html>
?>