<?php
/*
 * Created on 27-Dec-2006
 *
 * Action script for adderess
 */
 
include_once "config/config.phtml";
include_once "framework/sajax/Sajax.php";
include_once "guiUtil.phtml";
include_once "Entity/View/BrokerView.phtml";


function getBrokerList($index, $brokerID){
	$brokerView = new BrokerView();
	$brokerArguments = array("index"=>$index, "mode"=>"edit", "BrokerID"=>$brokerID, "DisplayType"=>"LIST");
	return $brokerView->getExistingHTMLForm($brokerArguments);
}

function getBrokerDetail($index, $brokerID){
	$brokerView = new BrokerView();
	$brokerArguments = array("index"=>$index, "mode"=>"display", "BrokerID"=>$brokerID, "DisplayType"=>"CONTACT");
	return $brokerView->getExistingHTMLForm($brokerArguments);
}

sajax_export("getBrokerList", "getBrokerDetail");
?>