<?php
/*
 * Created on 12-Jan-2007
 *
 * Sice  transactions record is not supposed to be added dynamically, so
 * this class is not available for AJAX. Only cheque has AJAX call.
 */
 
include_once "config/config.phtml";
include_once "guiUtil.phtml";
require_once "Entity/View/ChequeView.phtml";
include_once "framework/sajax/Sajax.php";

function getNewChequeHTMLForm($index, $inputPrefix = ""){
	$cheque = new ChequeView();
	$cheque->setInputPrefix($inputPrefix);
	$arguments = array();
	$arguments['Index'] = $index;
	return $cheque->getNewHTMLForm($arguments);
}

function getExistingChequeHTMLForm($index, $arguments, $inputPrefix = "", $mode = "display"){
	$cheque = new ChequeView();
	$cheque->setInputPrefix($inputPrefix);
	$arguments['Index'] = $index;
	$arguments['Mode'] = $mode;
	$result =  $cheque->getExistingHTMLForm($arguments);
	return $result;
}

// should be initialized by caller
//sajax_init();
//$sajax_debug_mode = 1;
sajax_export("getNewChequeHTMLForm");
// should be handled by caller
//sajax_handle_client_request();
//
?><?
//<html>
//<body>
//<form>
//<?= getNewChequeHTMLForm(1); 
//</form>
//</body>
//</html>
?>