<?php
/*
 * Created on 12-Jan-2007
 *
 * Sice deposit transactions record is not supposed to be added dynamically, so
 * this class is not available for AJAX. Only cheque has AJAX call.
 */
 
include_once "config/config.phtml";
include_once "guiUtil.phtml";
require_once "Entity/View/DepositChequeView.phtml";
include_once "framework/sajax/Sajax.php";

function getNewDepositChequeHTMLForm($index, $inputPrefix = ""){
	$depositCheque = new DepositChequeView();
	$depositCheque->setInputPrefix($inputPrefix);
	$arguments = array();
	$arguments['Index'] = $index;
	return $depositCheque->getNewHTMLForm($arguments);
}

function getExistingDepositChequeHTMLForm($index, $arguments, $inputPrefix = "", $mode = "display"){
	$depositCheque = new DepositChequeView();
	$depositCheque->setInputPrefix($inputPrefix);
	$arguments['Index'] = $index;
	$arguments['Mode'] = $mode;
	$result =  $depositCheque->getExistingHTMLForm($arguments);
	return $result;
}

// should be initialized by caller
//sajax_init();
//$sajax_debug_mode = 1;
sajax_export("getNewDepositChequeHTMLForm");
// should be handled by caller
//sajax_handle_client_request();
//
?><?
//<html>
//<body>
//<form>
//<?= getNewDepositChequeHTMLForm(1); 
//</form>
//</body>
//</html>
?>