<?php
/*
 * Created on 12-Jan-2007
 *
 * Sice deposit transactions record is not supposed to be added dynamically, so
 * this class is not available for AJAX. Only cheque has AJAX call.
 */
 
include_once "config/config.phtml";
include_once "guiUtil.phtml";
require "Entity/Controller/DepositChequeAction.phtml";
require "Entity/View/DepositTransactionsRecordView.phtml";

function getNewDepositTransactionsRecordHTMLForm($index){
	$depositTransactionsRecord = new DepositTransactionsRecordView();
	return $depositTransactionsRecord->getNewHTMLForm($index);
}

function getExistingDepositTransactionsRecordHTMLForm($index, $DBResultRow, $mode = "display"){
	$depositTransactionsRecord = new DepositTransactionsRecordView();
	return $depositTransactionsRecord->getExistingHTMLForm($index, $DBResultRow, $mode);
}
?><?
//<html>
//<script language="javascript">
//<? sajax_show_javascript(); 
//</script>
// getExistingDepositTransactionsRecordHTMLForm(2, array("TransactionsRecordID" => 1), "edit"); 
//</html>
?>