<?php
/*
 * Created on 2007-11-19
 *
 * Sice  transactions record is not supposed to be added dynamically, so
 * this class is not available for AJAX. Only InventoryItem has AJAX call.
 */
 
include_once "config/config.phtml";
include_once "guiUtil.phtml";
require_once "Entity/View/InventoryItemView.phtml";
include_once "framework/sajax/Sajax.php";

function getNewInventoryItemHTMLForm($index){
	$InventoryItem = new InventoryItemView();
	$InventoryItem->setInputPrefix($inputPrefix);
	$arguments = array();
	$arguments['Index'] = $index;
	return $InventoryItem->getNewHTMLForm($arguments);
}

function getExistingInventoryItemHTMLForm($index, $arguments, $inputPrefix = "", $mode = "display"){
	$InventoryItem = new InventoryItemView();
	$InventoryItem->setInputPrefix($inputPrefix);
	$arguments['Index'] = $index;
	$arguments['Mode'] = $mode;
	$result =  $InventoryItem->getExistingHTMLForm($arguments);
	return $result;
}

// should be initialized by caller
//sajax_init();
//$sajax_debug_mode = 1;
sajax_export("getNewInventoryItemHTMLForm");
// should be handled by caller
//sajax_handle_client_request();
//
?><?
//<html>
//<body>
//<form>
//<?= getNewInventoryItemHTMLForm(1); 
//</form>
//</body>
//</html>
?>