<?php
/*
 * Created on 12-Jan-2007
 *
 * Sice deposit transactions record is not supposed to be added dynamically, so
 * this class is not available for AJAX. Only cheque has AJAX call.
 */
 
include_once "config/config.phtml";
include_once "guiUtil.phtml";
require "Entity/Controller/ChequeAction.phtml";
require "Entity/View/TransactionsRecordView.phtml";

function getNewTransactionsRecordHTMLForm($index){
	$depositTransactionsRecord = new TransactionsRecordView();
	return $depositTransactionsRecord->getNewHTMLForm($index);
}

function getExistingTransactionsRecordHTMLForm($index, $DBResultRow, $mode = "display"){
	$depositTransactionsRecord = new TransactionsRecordView();
	return $depositTransactionsRecord->getExistingHTMLForm($index, $DBResultRow, $mode);
}
?>